--------------------------------------------------------
--  DDL for Table POS_PRODUCTS_PROMO_DETAILS
--------------------------------------------------------

  CREATE TABLE "POS_PRODUCTS_PROMO_DETAILS" ("PROMO_DETAIL_ID" NUMBER, "PRODUCT_ID" NUMBER, "PROMOTION_ID" NUMBER(15,0), "START_DATE" DATE, "END_DATE" DATE, "CREATED_BY" NUMBER(10,0), "CREATION_DATE" DATE, "LAST_UPDATED_BY" NUMBER(10,0), "LAST_UPDATE_DATE" DATE, "OBJECT_VERSION_ID" NUMBER)  DEFAULT COLLATION "USING_NLS_COMP"
