--------------------------------------------------------
--  DDL for Table POS_CASHIERS
--------------------------------------------------------

  CREATE TABLE "POS_CASHIERS" ("CASHIER_ID" NUMBER(15,0), "PARTIY_ID" NUMBER(15,0), "CASHIER_NUMBER" NUMBER, "CASHIER_TYPE" VARCHAR2(1 CHAR) COLLATE "USING_NLS_COMP", "DESCRIPTION" VARCHAR2(4000 CHAR) COLLATE "USING_NLS_COMP", "LOGIN_USER" VARCHAR2(20 CHAR) COLLATE "USING_NLS_COMP", "LOGIN_PASSWORD" VARCHAR2(100 CHAR) COLLATE "USING_NLS_COMP", "ENABLED_FLAG" VARCHAR2(1 CHAR) COLLATE "USING_NLS_COMP", "HOLD_FLAG" VARCHAR2(1 CHAR) COLLATE "USING_NLS_COMP", "START_DATE" DATE, "END_DATE" DATE, "CREATED_BY" NUMBER(10,0), "CREATION_DATE" DATE, "LAST_UPDATED_BY" NUMBER(10,0), "LAST_UPDATE_DATE" DATE, "OBJECT_VERSION_ID" NUMBER)  DEFAULT COLLATION "USING_NLS_COMP" 

   COMMENT ON COLUMN "POS_CASHIERS"."ENABLED_FLAG" IS 'identifier id'
   COMMENT ON COLUMN "POS_CASHIERS"."HOLD_FLAG" IS 'identifier id'
