--------------------------------------------------------
--  DDL for Table POS_CUSTOMERS
--------------------------------------------------------

  CREATE TABLE "POS_CUSTOMERS" ("CUSTOMER_ID" NUMBER(15,0), "PARTIY_ID" NUMBER(15,0), "CUSTOMER_NUMBER" VARCHAR2(30) COLLATE "USING_NLS_COMP", "DESCRIPTION" VARCHAR2(4000 CHAR) COLLATE "USING_NLS_COMP", "REGISTERED_DATE" DATE, "ENABLED_FLAG" VARCHAR2(1 CHAR) COLLATE "USING_NLS_COMP", "HOLD_FLAG" VARCHAR2(1 CHAR) COLLATE "USING_NLS_COMP", "START_DATE" DATE, "END_DATE" DATE, "GENDER" VARCHAR2(1 CHAR) COLLATE "USING_NLS_COMP", "IDENTIFIER_TYPE" VARCHAR2(1 CHAR) COLLATE "USING_NLS_COMP", "IDENTIFIER_NUMBER" VARCHAR2(100 CHAR) COLLATE "USING_NLS_COMP", "MOBILE_NUMBER" VARCHAR2(30 CHAR) COLLATE "USING_NLS_COMP", "PHONE_NUMBER" VARCHAR2(30 CHAR) COLLATE "USING_NLS_COMP", "ADDRESS" VARCHAR2(200 CHAR) COLLATE "USING_NLS_COMP", "CREDIT_LIMIT" NUMBER(13,2), "CHILDREN_UNDER_18" VARCHAR2(1 CHAR) COLLATE "USING_NLS_COMP", "LOGIN_USER" VARCHAR2(20 CHAR) COLLATE "USING_NLS_COMP", "LOGIN_PASSWORD" VARCHAR2(30 CHAR) COLLATE "USING_NLS_COMP", "CREATED_BY" NUMBER(10,0), "CREATION_DATE" DATE, "LAST_UPDATED_BY" NUMBER(10,0), "LAST_UPDATE_DATE" DATE, "OBJECT_VERSION_ID" NUMBER)  DEFAULT COLLATION "USING_NLS_COMP" 

   COMMENT ON COLUMN "POS_CUSTOMERS"."ENABLED_FLAG" IS 'identifier id'
   COMMENT ON COLUMN "POS_CUSTOMERS"."HOLD_FLAG" IS 'identifier id'
   COMMENT ON COLUMN "POS_CUSTOMERS"."GENDER" IS 'identifier id'
   COMMENT ON COLUMN "POS_CUSTOMERS"."IDENTIFIER_TYPE" IS 'identifier id'
   COMMENT ON COLUMN "POS_CUSTOMERS"."IDENTIFIER_NUMBER" IS 'identifier id'
   COMMENT ON COLUMN "POS_CUSTOMERS"."CHILDREN_UNDER_18" IS 'identifier id'
