--------------------------------------------------------
--  DDL for Table POS_PAYMENTS
--------------------------------------------------------

  CREATE TABLE "POS_PAYMENTS" ("PAYMENT_ID" NUMBER DEFAULT "DL_POS_PAYMENT_ID_S"."NEXTVAL", "PAY_METHOD_ID" NUMBER, "INVOICE_ID" NUMBER(15,0), "PAYMENT_TYPE" VARCHAR2(1 CHAR) COLLATE "USING_NLS_COMP", "PAYMENT_NUMBER" VARCHAR2(30 CHAR) COLLATE "USING_NLS_COMP", "DESCRIPTION" VARCHAR2(4000 CHAR) COLLATE "USING_NLS_COMP", "PAYMENT_DATE" DATE, "PAYMENT_CURRANCY" VARCHAR2(3 CHAR) COLLATE "USING_NLS_COMP", "AMOUNT" NUMBER(7,3), "STATUS" VARCHAR2(1 CHAR) COLLATE "USING_NLS_COMP", "ENABLED_FLAG" VARCHAR2(1 CHAR) COLLATE "USING_NLS_COMP", "START_DATE" DATE, "END_DATE" DATE, "CREATED_BY" VARCHAR2(60 CHAR) COLLATE "USING_NLS_COMP", "CREATION_DATE" DATE, "LAST_UPDATED_BY" VARCHAR2(60 CHAR) COLLATE "USING_NLS_COMP", "LAST_UPDATE_DATE" DATE, "OBJECT_VERSION_ID" NUMBER)  DEFAULT COLLATION "USING_NLS_COMP"
