--------------------------------------------------------
--  DDL for Table POS_STORE_BRANCHS
--------------------------------------------------------

  CREATE TABLE "POS_STORE_BRANCHS" ("BRANCH_ID" NUMBER(10,0), "STORE_ID" NUMBER(15,0), "SHORT_NAME" VARCHAR2(50 CHAR) COLLATE "USING_NLS_COMP", "NAME" VARCHAR2(100 CHAR) COLLATE "USING_NLS_COMP", "DESCRIPTION" VARCHAR2(4000 CHAR) COLLATE "USING_NLS_COMP", "PARENT_ID" NUMBER(10,0), "MANAGER_ID" NUMBER(10,0), "ENABLED_FLAG" VARCHAR2(1 CHAR) COLLATE "USING_NLS_COMP", "START_DATE" DATE, "END_DATE" DATE, "CREATED_BY" NUMBER(10,0), "CREATION_DATE" DATE, "LAST_UPDATED_BY" NUMBER(10,0), "LAST_UPDATE_DATE" DATE, "OBJECT_VERSION_ID" NUMBER)  DEFAULT COLLATION "USING_NLS_COMP"
