--------------------------------------------------------
--  DDL for Table POS_PARTIES
--------------------------------------------------------

  CREATE TABLE "POS_PARTIES" ("PARTIY_ID" NUMBER(15,0), "PARTY_TYPE" VARCHAR2(1 CHAR) COLLATE "USING_NLS_COMP", "PARTY_NUMBER" VARCHAR2(30) COLLATE "USING_NLS_COMP", "PARTY_NAME" VARCHAR2(360 CHAR) COLLATE "USING_NLS_COMP", "DESCRIPTION" VARCHAR2(4000 CHAR) COLLATE "USING_NLS_COMP", "PERSON_TITLE" VARCHAR2(3 CHAR) COLLATE "USING_NLS_COMP", "PERSON_FIRST_NAME" VARCHAR2(100 CHAR) COLLATE "USING_NLS_COMP", "PERSON_MIDDLE_NAME" VARCHAR2(100 CHAR) COLLATE "USING_NLS_COMP", "PERSON_LAST_NAME" VARCHAR2(100 CHAR) COLLATE "USING_NLS_COMP", "PERSON_NICE_NAME" VARCHAR2(100 CHAR) COLLATE "USING_NLS_COMP", "PERSON_GENDER" VARCHAR2(1 CHAR) COLLATE "USING_NLS_COMP", "PERSON_MARITAL_STATUS" VARCHAR2(1 CHAR) COLLATE "USING_NLS_COMP", "DATE_OF_BIRTH" DATE, "ENABLED_FLAG" VARCHAR2(1 CHAR) COLLATE "USING_NLS_COMP", "HOLD_FLAG" VARCHAR2(1 CHAR) COLLATE "USING_NLS_COMP", "START_DATE" DATE, "END_DATE" DATE, "CREATED_BY" NUMBER(10,0), "CREATION_DATE" DATE, "LAST_UPDATED_BY" NUMBER(10,0), "LAST_UPDATE_DATE" DATE, "OBJECT_VERSION_ID" NUMBER)  DEFAULT COLLATION "USING_NLS_COMP" 

   COMMENT ON COLUMN "POS_PARTIES"."PARTY_TYPE" IS 'P Person, O Orgnization'
   COMMENT ON COLUMN "POS_PARTIES"."PERSON_MIDDLE_NAME" IS 'Middle Name'
