--------------------------------------------------------
--  DDL for Table POS_PRODUCT_TRANSACTIONS
--------------------------------------------------------

  CREATE TABLE "POS_PRODUCT_TRANSACTIONS" ("TRANSACTION_ID" NUMBER(15,0), "WAREHOUSE_ID" NUMBER(15,0), "PRODUCT_ID" NUMBER, "TRX_NUMBER" VARCHAR2(100 CHAR) COLLATE "USING_NLS_COMP", "DESCRIPTION" VARCHAR2(4000 CHAR) COLLATE "USING_NLS_COMP", "TYPE" VARCHAR2(1 CHAR) COLLATE "USING_NLS_COMP", "QUANTITY" NUMBER(7,0), "CANCEL_FLAG" VARCHAR2(1 CHAR) COLLATE "USING_NLS_COMP", "CANCELED_BY" NUMBER(10,0), "CANCEL_REASON" VARCHAR2(1000 CHAR) COLLATE "USING_NLS_COMP", "START_DATE" DATE, "END_DATE" DATE, "CREATED_BY" NUMBER(10,0), "CREATION_DATE" DATE, "LAST_UPDATED_BY" NUMBER(10,0), "LAST_UPDATE_DATE" DATE, "OBJECT_VERSION_ID" NUMBER)  DEFAULT COLLATION "USING_NLS_COMP"
