--------------------------------------------------------
--  DDL for Table POS_ORDER_LINES
--------------------------------------------------------

  CREATE TABLE "POS_ORDER_LINES" ("ORDER_LINE_ID" NUMBER(15,0), "ORDER_ID" NUMBER(15,0), "LINE_NUM" NUMBER(2,0), "LINE_TYPE" VARCHAR2(1 CHAR) COLLATE "USING_NLS_COMP", "PRODUCT_ID" NUMBER, "SERVICE_ID" NUMBER, "PRICE" NUMBER(7,3), "QUANTITY" NUMBER(7,0), "AMOUNT" NUMBER(7,3), "DESCRIPTION" VARCHAR2(4000 CHAR) COLLATE "USING_NLS_COMP", "CANCEL_FLAG" VARCHAR2(1 CHAR) COLLATE "USING_NLS_COMP", "CANCELED_BY" NUMBER, "CANCEL_REASON" VARCHAR2(1000 CHAR) COLLATE "USING_NLS_COMP", "START_DATE" DATE, "END_DATE" DATE, "CREATED_BY" NUMBER(10,0), "CREATION_DATE" DATE, "LAST_UPDATED_BY" NUMBER(10,0), "LAST_UPDATE_DATE" DATE, "OBJECT_VERSION_ID" NUMBER)  DEFAULT COLLATION "USING_NLS_COMP" 

   COMMENT ON COLUMN "POS_ORDER_LINES"."LINE_TYPE" IS 'P Product
S Service'
