SET DEFINE OFF;
--
-- DEMASYLABS  (User) 
--
CREATE USER DEMASYLABS
  IDENTIFIED BY <password>
  HTTP DIGEST DISABLE
  DEFAULT TABLESPACE SYSTEM
  TEMPORARY TABLESPACE TEMP
  PROFILE DEFAULT
  ACCOUNT UNLOCK
  ENABLE EDITIONS
/

-- 4 Roles for DEMASYLABS 
--
-- CONNECT  (Role) 
--
GRANT CONNECT TO DEMASYLABS
/
--
-- DB_DEVELOPER_ROLE  (Role) 
--
GRANT DB_DEVELOPER_ROLE TO DEMASYLABS
/
--
-- RESOURCE  (Role) 
--
GRANT RESOURCE TO DEMASYLABS
/
--
-- SELECT_CATALOG_ROLE  (Role) 
--
GRANT SELECT_CATALOG_ROLE TO DEMASYLABS
/
ALTER USER DEMASYLABS DEFAULT ROLE ALL
/

-- 21 System Privileges for DEMASYLABS 
GRANT ALTER SESSION TO DEMASYLABS
/
GRANT CREATE ANY EDITION TO DEMASYLABS
/
GRANT CREATE ANY INDEX TO DEMASYLABS
/
GRANT CREATE ANY PROCEDURE TO DEMASYLABS
/
GRANT CREATE ANY SEQUENCE TO DEMASYLABS
/
GRANT CREATE ANY TABLE TO DEMASYLABS
/
GRANT CREATE ANY TRIGGER TO DEMASYLABS
/
GRANT CREATE ANY TYPE TO DEMASYLABS
/
GRANT CREATE ANY VIEW TO DEMASYLABS
/
GRANT CREATE DATABASE LINK TO DEMASYLABS
/
GRANT CREATE JOB TO DEMASYLABS
/
GRANT CREATE MATERIALIZED VIEW TO DEMASYLABS
/
GRANT CREATE PROCEDURE TO DEMASYLABS
/
GRANT CREATE SEQUENCE TO DEMASYLABS
/
GRANT CREATE SESSION TO DEMASYLABS
/
GRANT CREATE SYNONYM TO DEMASYLABS
/
GRANT CREATE TABLE TO DEMASYLABS
/
GRANT CREATE TRIGGER TO DEMASYLABS
/
GRANT CREATE TYPE TO DEMASYLABS
/
GRANT CREATE VIEW TO DEMASYLABS
/
GRANT UNLIMITED TABLESPACE TO DEMASYLABS
/