--------------------------------------------------------
--  DDL for Table POS_ORDERS
--------------------------------------------------------

  CREATE TABLE "POS_ORDERS" ("ORDER_ID" NUMBER(15,0), "BRANCH_ID" NUMBER(10,0), "CASHIER_ID" NUMBER(15,0), "CUSTOMER_ID" NUMBER(15,0), "ORDER_TYPE" VARCHAR2(1 CHAR) COLLATE "USING_NLS_COMP", "ORDER_NUMBER" VARCHAR2(30 CHAR) COLLATE "USING_NLS_COMP", "ORDER_DATE" DATE, "STATUS" VARCHAR2(30 CHAR) COLLATE "USING_NLS_COMP", "DESCRIPTION" VARCHAR2(2000 CHAR) COLLATE "USING_NLS_COMP", "ENABLED_FLAG" VARCHAR2(1 CHAR) COLLATE "USING_NLS_COMP", "HOLD_FLAG" VARCHAR2(1 CHAR) COLLATE "USING_NLS_COMP", "GIFTWRAP_FLAG" VARCHAR2(1 CHAR) COLLATE "USING_NLS_COMP", "GIFTWRAP_MESSAGE" VARCHAR2(2000 CHAR) COLLATE "USING_NLS_COMP", "START_DATE" DATE, "END_DATE" DATE, "CREATED_BY" NUMBER(10,0), "CREATION_DATE" DATE, "LAST_UPDATED_BY" NUMBER(10,0), "LAST_UPDATE_DATE" DATE, "OBJECT_VERSION_ID" NUMBER)  DEFAULT COLLATION "USING_NLS_COMP" 

   COMMENT ON COLUMN "POS_ORDERS"."ENABLED_FLAG" IS 'identifier id'
   COMMENT ON COLUMN "POS_ORDERS"."HOLD_FLAG" IS 'identifier id'
