SET DEFINE OFF;
CREATE TABLE DEMASYLABS.POS_PAYMENT_METHODS
(
  METHOD_ID          NUMBER CONSTRAINT PPMS_METHOD_ID_NNC NOT NULL,
  METHOD_TYPE        VARCHAR2(1 CHAR) CONSTRAINT PPMS_METHOD_TYPE_NNC NOT NULL,
  SHORT_NAME         VARCHAR2(30 CHAR) CONSTRAINT PPMS_SHORT_NAME_NNC NOT NULL,
  METHOD_NAME        VARCHAR2(100 CHAR) CONSTRAINT PPMS_METHOD_NAME_NNC NOT NULL,
  DESCRIPTION        VARCHAR2(4000 CHAR),
  DEFAULT_FLAG       VARCHAR2(1 CHAR)           DEFAULT 'N',
  CASH_FLAG          VARCHAR2(1 CHAR)           DEFAULT 'N',
  HOLD_FLAG          VARCHAR2(1 CHAR)           DEFAULT 'N',
  STATUS_CODE        VARCHAR2(30 CHAR)          DEFAULT 'A' CONSTRAINT PPMS_STATUS_CODE_NNC NOT NULL,
  ENABLED_FLAG       VARCHAR2(1 CHAR)           DEFAULT 'Y' CONSTRAINT PPMS_ENABLED_FLAG_NNC NOT NULL,
  START_DATE         DATE                       DEFAULT sysdate CONSTRAINT PPMS_START_DATE_NNC NOT NULL,
  END_DATE           DATE,
  CREATED_BY         NUMBER CONSTRAINT PPMS_CREATED_BY_NNC NOT NULL,
  CREATION_DATE      DATE CONSTRAINT PPMS_CREATION_DATE_NNC NOT NULL,
  LAST_UPDATED_BY    NUMBER CONSTRAINT PPMS_LAST_UPDATED_BY_NNC NOT NULL,
  LAST_UPDATE_DATE   DATE CONSTRAINT PPMS_LAST_UPDATE_DATE_NNC NOT NULL,
  OBJECT_VERSION_ID  NUMBER CONSTRAINT PPMS_OBJECT_VERSION_ID_NNC NOT NULL,
  CONSTRAINT PPMS_CASH_FLAG_CK
  CHECK ( cash_flag IN ( 'N', 'Y' ) )
  ENABLE VALIDATE
,  CONSTRAINT PPMS_DEFAULT_FLAG_CK
  CHECK ( default_flag IN ( 'N', 'Y' ) )
  ENABLE VALIDATE
,  CONSTRAINT PPMS_ENABLED_FLAG_CK
  CHECK ( enabled_flag IN ( 'N', 'Y' ) )
  ENABLE VALIDATE
,  CONSTRAINT PPMS_HOLD_FLAG_CK
  CHECK ( hold_flag IN ( 'N', 'Y' ) )
  ENABLE VALIDATE
,  CONSTRAINT PPMS_METHOD_TYPE_CK
  CHECK ( method_type IN ( 'BT', 'C', 'CC', 'CK', 'DC',
                                 'GC', 'MP', 'O', 'SC' ) )
  ENABLE VALIDATE
,  CONSTRAINT PPMS_STATUS_CODE_CK
  CHECK ( status_code IN ( 'A', 'D', 'I', 'P' ) )
  ENABLE VALIDATE
,  CONSTRAINT PPMS_METHOD_ID_PK
  PRIMARY KEY
  (METHOD_ID)
  ENABLE VALIDATE
,  CONSTRAINT PPMS_METHOD_NAME_UN
  UNIQUE (METHOD_NAME)
  ENABLE VALIDATE
,  CONSTRAINT PPMS_SHORT_NAME_UN
  UNIQUE (SHORT_NAME)
  ENABLE VALIDATE
)
LOGGING 
NOCOMPRESS 
NO INMEMORY
NOCACHE
RESULT_CACHE (MODE DEFAULT)
NOPARALLEL
/

COMMENT ON TABLE DEMASYLABS.POS_PAYMENT_METHODS IS 'Payment methods configuration for point-of-sale transactions. Defines available payment options with validation rules and display preferences for the checkout process.'
/

COMMENT ON COLUMN DEMASYLABS.POS_PAYMENT_METHODS.METHOD_ID IS 'Unique payment method identifier (Primary Key)'
/

COMMENT ON COLUMN DEMASYLABS.POS_PAYMENT_METHODS.METHOD_TYPE IS 'Short display name for payment method (UI displays)'
/

COMMENT ON COLUMN DEMASYLABS.POS_PAYMENT_METHODS.SHORT_NAME IS 'Short display name for payment method (UI displays)'
/

COMMENT ON COLUMN DEMASYLABS.POS_PAYMENT_METHODS.METHOD_NAME IS 'Full descriptive name of the payment method'
/

COMMENT ON COLUMN DEMASYLABS.POS_PAYMENT_METHODS.DESCRIPTION IS 'Detailed description of payment method and usage instructions'
/

COMMENT ON COLUMN DEMASYLABS.POS_PAYMENT_METHODS.DEFAULT_FLAG IS 'Indicates if this is the default payment method (Y/N)'
/

COMMENT ON COLUMN DEMASYLABS.POS_PAYMENT_METHODS.CASH_FLAG IS 'Indicates if this is a cash-based payment method (Y/N)'
/

COMMENT ON COLUMN DEMASYLABS.POS_PAYMENT_METHODS.HOLD_FLAG IS 'Payment method on hold flag for maintenance (Y/N)'
/

COMMENT ON COLUMN DEMASYLABS.POS_PAYMENT_METHODS.STATUS_CODE IS 'Product operational status: A=Active, I=Inactive, D=Discontinued, P=Pending'
/

COMMENT ON COLUMN DEMASYLABS.POS_PAYMENT_METHODS.ENABLED_FLAG IS 'Active status flag (Y/N)'
/

COMMENT ON COLUMN DEMASYLABS.POS_PAYMENT_METHODS.START_DATE IS 'Effective start date'
/

COMMENT ON COLUMN DEMASYLABS.POS_PAYMENT_METHODS.END_DATE IS 'Effective end date'
/

COMMENT ON COLUMN DEMASYLABS.POS_PAYMENT_METHODS.CREATED_BY IS 'User who created the record'
/

COMMENT ON COLUMN DEMASYLABS.POS_PAYMENT_METHODS.CREATION_DATE IS 'Record creation timestamp'
/

COMMENT ON COLUMN DEMASYLABS.POS_PAYMENT_METHODS.LAST_UPDATED_BY IS 'User who last updated the record'
/

COMMENT ON COLUMN DEMASYLABS.POS_PAYMENT_METHODS.LAST_UPDATE_DATE IS 'Last update timestamp'
/

COMMENT ON COLUMN DEMASYLABS.POS_PAYMENT_METHODS.OBJECT_VERSION_ID IS 'Optimistic locking version number'
/
