SET DEFINE OFF;
CREATE TABLE DEMASYLABS.POS_ORDER_LINES
(
  ORDER_LINE_ID      NUMBER CONSTRAINT POL_ORDER_LINE_ID_NNC NOT NULL,
  ORDER_ID           NUMBER CONSTRAINT POL_ORDER_ID_NNC NOT NULL,
  LINE_NUM           NUMBER(2) CONSTRAINT POL_LINE_NUM_NNC NOT NULL,
  LINE_TYPE          VARCHAR2(1 CHAR) CONSTRAINT POL_LINE_TYPE_NNC NOT NULL,
  PRODUCT_ID         NUMBER CONSTRAINT POL_PRODUCT_ID_NNC NOT NULL,
  SERVICE_ID         NUMBER,
  PRICE              NUMBER(7,5),
  QUANTITY           NUMBER(7,3),
  AMOUNT             NUMBER(7,5),
  DESCRIPTION        VARCHAR2(4000 CHAR),
  CANCEL_FLAG        VARCHAR2(1 CHAR),
  CANCELED_BY        NUMBER,
  CANCEL_REASON      VARCHAR2(1000 CHAR),
  STATUS_CODE        VARCHAR2(30 CHAR)          DEFAULT 'A' CONSTRAINT POL_STATUS_CODE_NNC NOT NULL,
  ENABLED_FLAG       VARCHAR2(1 CHAR)           DEFAULT 'Y' CONSTRAINT POL_ENABLED_FLAG_NNC NOT NULL,
  START_DATE         DATE                       DEFAULT sysdate CONSTRAINT POL_START_DATE_NNC NOT NULL,
  END_DATE           DATE,
  CREATED_BY         NUMBER CONSTRAINT POL_CREATED_BY_NNC NOT NULL,
  CREATION_DATE      DATE CONSTRAINT POL_CREATION_DATE_NNC NOT NULL,
  LAST_UPDATED_BY    NUMBER CONSTRAINT POL_LAST_UPDATED_BY_NNC NOT NULL,
  LAST_UPDATE_DATE   DATE CONSTRAINT POL_LAST_UPDATE_DATE_NNC NOT NULL,
  OBJECT_VERSION_ID  NUMBER CONSTRAINT POL_OBJECT_VERSION_ID_NNC NOT NULL,
  CONSTRAINT POL_CANCEL_FLAG_CK
  CHECK ( cancel_flag IN ( 'N', 'Y' ) )
  ENABLE VALIDATE
,  CONSTRAINT POL_ENABLED_FLAG_CK
  CHECK ( enabled_flag IN ( 'N', 'Y' ) )
  ENABLE VALIDATE
,  CONSTRAINT POL_LINE_NUM_CK
  CHECK ( line_num BETWEEN 1 AND 99 )
  ENABLE VALIDATE
,  CONSTRAINT POL_LINE_TYPE_CK
  CHECK ( line_type IN ( 'P', 'S' ) )
  ENABLE VALIDATE
,  CONSTRAINT POL_STATUS_CODE_CK
  CHECK ( status_code IN ( 'A', 'D', 'I', 'P' ) )
  ENABLE VALIDATE
,  CONSTRAINT POL_ORDER_LINE_ID_PK
  PRIMARY KEY
  (ORDER_LINE_ID)
  ENABLE VALIDATE
,  CONSTRAINT POL_ORDER_ID_FK 
  FOREIGN KEY (ORDER_ID) 
  REFERENCES DEMASYLABS.POS_ORDERS (ORDER_ID)
  ENABLE VALIDATE
,  CONSTRAINT POL_PRODUCT_ID_FK 
  FOREIGN KEY (PRODUCT_ID) 
  REFERENCES DEMASYLABS.POS_PRODUCTS (PRODUCT_ID)
  ENABLE VALIDATE
)
LOGGING 
NOCOMPRESS 
NO INMEMORY
NOCACHE
RESULT_CACHE (MODE DEFAULT)
NOPARALLEL
/

COMMENT ON TABLE DEMASYLABS.POS_ORDER_LINES IS 'Order line items for customer orders. Each line represents either a product or service with pricing, quantity, and amount calculation. Supports complete order management workflow with cancellation capabilities.'
/

COMMENT ON COLUMN DEMASYLABS.POS_ORDER_LINES.ORDER_LINE_ID IS 'Unique order line identifier (Primary Key)'
/

COMMENT ON COLUMN DEMASYLABS.POS_ORDER_LINES.ORDER_ID IS 'Parent order identifier (FK to pos_orders)'
/

COMMENT ON COLUMN DEMASYLABS.POS_ORDER_LINES.LINE_NUM IS 'Sequential line number within the order (1-99)'
/

COMMENT ON COLUMN DEMASYLABS.POS_ORDER_LINES.LINE_TYPE IS 'Line type: P=Product, S=Service'
/

COMMENT ON COLUMN DEMASYLABS.POS_ORDER_LINES.PRODUCT_ID IS 'Product identifier for product lines (FK to pos_products)'
/

COMMENT ON COLUMN DEMASYLABS.POS_ORDER_LINES.SERVICE_ID IS 'Service identifier for service lines (FK to pos_services)'
/

COMMENT ON COLUMN DEMASYLABS.POS_ORDER_LINES.PRICE IS 'Unit price for the product or service'
/

COMMENT ON COLUMN DEMASYLABS.POS_ORDER_LINES.QUANTITY IS 'Quantity ordered (units, hours, etc.)'
/

COMMENT ON COLUMN DEMASYLABS.POS_ORDER_LINES.AMOUNT IS 'Total line amount (price × quantity)'
/

COMMENT ON COLUMN DEMASYLABS.POS_ORDER_LINES.DESCRIPTION IS 'Additional line description or special instructions'
/

COMMENT ON COLUMN DEMASYLABS.POS_ORDER_LINES.CANCEL_FLAG IS 'Line cancellation flag (Y/N)'
/

COMMENT ON COLUMN DEMASYLABS.POS_ORDER_LINES.CANCELED_BY IS 'User who canceled the line'
/

COMMENT ON COLUMN DEMASYLABS.POS_ORDER_LINES.CANCEL_REASON IS 'Reason for line cancellation'
/

COMMENT ON COLUMN DEMASYLABS.POS_ORDER_LINES.STATUS_CODE IS 'Product operational status: A=Active, I=Inactive, D=Discontinued, P=Pending'
/

COMMENT ON COLUMN DEMASYLABS.POS_ORDER_LINES.ENABLED_FLAG IS 'Active status flag (Y/N)'
/

COMMENT ON COLUMN DEMASYLABS.POS_ORDER_LINES.START_DATE IS 'Effective start date'
/

COMMENT ON COLUMN DEMASYLABS.POS_ORDER_LINES.END_DATE IS 'Effective end date'
/

COMMENT ON COLUMN DEMASYLABS.POS_ORDER_LINES.CREATED_BY IS 'User who created the record'
/

COMMENT ON COLUMN DEMASYLABS.POS_ORDER_LINES.CREATION_DATE IS 'Record creation timestamp'
/

COMMENT ON COLUMN DEMASYLABS.POS_ORDER_LINES.LAST_UPDATED_BY IS 'User who last updated the record'
/

COMMENT ON COLUMN DEMASYLABS.POS_ORDER_LINES.LAST_UPDATE_DATE IS 'Last update timestamp'
/

COMMENT ON COLUMN DEMASYLABS.POS_ORDER_LINES.OBJECT_VERSION_ID IS 'Optimistic locking version number'
/
