SET DEFINE OFF;
CREATE TABLE DEMASYLABS.POS_PAYMENTS
(
  PAYMENT_ID         NUMBER CONSTRAINT PPAY_PAYMENT_ID_NNC NOT NULL,
  METHOD_ID          NUMBER CONSTRAINT PPAY_METHOD_ID_NNC NOT NULL,
  INVOICE_ID         NUMBER CONSTRAINT PPAY_INVOICE_ID_NNC NOT NULL,
  PAYMENT_TYPE       VARCHAR2(30 CHAR) CONSTRAINT PPAY_PAYMENT_TYPE_NNC NOT NULL,
  PAYMENT_NUMBER     VARCHAR2(30 CHAR) CONSTRAINT PPAY_PAYMENT_NUMBER_NNC NOT NULL,
  DESCRIPTION        VARCHAR2(4000 BYTE),
  PAYMENT_DATE       DATE CONSTRAINT PPAY_PAYMENT_DATE_NNC NOT NULL,
  PAYMENT_CURRENCY   VARCHAR2(3 CHAR) CONSTRAINT PPAY_PAYMENT_CURRENCY_NNC NOT NULL,
  AMOUNT             NUMBER(15,2) CONSTRAINT PPAY_AMOUNT_NNC NOT NULL,
  STATUS_CODE        VARCHAR2(30 CHAR)          DEFAULT 'A' CONSTRAINT PPAY_STATUS_CODE_NNC NOT NULL,
  ENABLED_FLAG       VARCHAR2(1 CHAR)           DEFAULT 'Y' CONSTRAINT PPAY_ENABLED_FLAG_NNC NOT NULL,
  START_DATE         DATE                       DEFAULT sysdate CONSTRAINT PPAY_START_DATE_NNC NOT NULL,
  END_DATE           DATE,
  CREATED_BY         NUMBER CONSTRAINT PPAY_CREATED_BY_NNC NOT NULL,
  CREATION_DATE      DATE CONSTRAINT PPAY_CREATION_DATE_NNC NOT NULL,
  LAST_UPDATED_BY    NUMBER CONSTRAINT PPAY_LAST_UPDATED_BY_NNC NOT NULL,
  LAST_UPDATE_DATE   DATE CONSTRAINT PPAY_LAST_UPDATE_DATE_NNC NOT NULL,
  OBJECT_VERSION_ID  NUMBER CONSTRAINT PPAY_OBJECT_VERSION_ID_NNC NOT NULL,
  CONSTRAINT PPAY_ENABLED_FLAG_CK
  CHECK ( enabled_flag IN ( 'N', 'Y' ) )
  ENABLE VALIDATE
,  CONSTRAINT PPAY_PAYMENT_CURRENCY_CK
  CHECK ( payment_currency IN ( 'AUD', 'CAD', 'EGP', 'EUR', 'GBP',
                                      'JPY', 'SAR', 'USD' ) )
  ENABLE VALIDATE
,  CONSTRAINT PPAY_PAYMENT_TYPE_CK
  CHECK ( payment_type IN ( 'A', 'C', 'P', 'R' ) )
  ENABLE VALIDATE
,  CONSTRAINT PPAY_STATUS_CODE_CK
  CHECK ( status_code IN ( 'A', 'D', 'I', 'P' ) )
  ENABLE VALIDATE
,  CONSTRAINT PPAY_PAYMENT_ID_PK
  PRIMARY KEY
  (PAYMENT_ID)
  ENABLE VALIDATE
,  CONSTRAINT PPAY_INVOICE_ID_FK 
  FOREIGN KEY (INVOICE_ID) 
  REFERENCES DEMASYLABS.POS_INVOICES (INVOICE_ID)
  ENABLE VALIDATE
,  CONSTRAINT PPAY_METHOD_ID_FK 
  FOREIGN KEY (METHOD_ID) 
  REFERENCES DEMASYLABS.POS_PAYMENT_METHODS (METHOD_ID)
  ENABLE VALIDATE
)
LOGGING 
NOCOMPRESS 
NO INMEMORY
NOCACHE
RESULT_CACHE (MODE DEFAULT)
NOPARALLEL
/

COMMENT ON TABLE DEMASYLABS.POS_PAYMENTS IS 'Payment transactions for point-of-sale orders. Records actual payment processing with method tracking and financial reconciliation support.'
/

COMMENT ON COLUMN DEMASYLABS.POS_PAYMENTS.PAYMENT_ID IS 'Unique payment transaction identifier (Primary Key)'
/

COMMENT ON COLUMN DEMASYLABS.POS_PAYMENTS.METHOD_ID IS 'Payment method used (Foreign Key to pos_payment_methods)'
/

COMMENT ON COLUMN DEMASYLABS.POS_PAYMENTS.INVOICE_ID IS 'Associated invoice identifier (Foreign Key to pos_invoices)'
/

COMMENT ON COLUMN DEMASYLABS.POS_PAYMENTS.PAYMENT_TYPE IS 'Payment type: P=Payment, R=Refund, A=Adjustment, C=Credit'
/

COMMENT ON COLUMN DEMASYLABS.POS_PAYMENTS.PAYMENT_NUMBER IS 'Unique payment reference number for tracking'
/

COMMENT ON COLUMN DEMASYLABS.POS_PAYMENTS.DESCRIPTION IS 'Payment transaction description and notes'
/

COMMENT ON COLUMN DEMASYLABS.POS_PAYMENTS.PAYMENT_DATE IS 'Date and time when payment was processed'
/

COMMENT ON COLUMN DEMASYLABS.POS_PAYMENTS.PAYMENT_CURRENCY IS 'Payment currency code (ISO 4217 standard)'
/

COMMENT ON COLUMN DEMASYLABS.POS_PAYMENTS.AMOUNT IS 'Payment amount in specified currency'
/

COMMENT ON COLUMN DEMASYLABS.POS_PAYMENTS.STATUS_CODE IS 'Product operational status: A=Active, I=Inactive, D=Discontinued, P=Pending'
/

COMMENT ON COLUMN DEMASYLABS.POS_PAYMENTS.ENABLED_FLAG IS 'Active status flag (Y/N)'
/

COMMENT ON COLUMN DEMASYLABS.POS_PAYMENTS.START_DATE IS 'Effective start date'
/

COMMENT ON COLUMN DEMASYLABS.POS_PAYMENTS.END_DATE IS 'Effective end date'
/

COMMENT ON COLUMN DEMASYLABS.POS_PAYMENTS.CREATED_BY IS 'User who created the record'
/

COMMENT ON COLUMN DEMASYLABS.POS_PAYMENTS.CREATION_DATE IS 'Record creation timestamp'
/

COMMENT ON COLUMN DEMASYLABS.POS_PAYMENTS.LAST_UPDATED_BY IS 'User who last updated the record'
/

COMMENT ON COLUMN DEMASYLABS.POS_PAYMENTS.LAST_UPDATE_DATE IS 'Last update timestamp'
/

COMMENT ON COLUMN DEMASYLABS.POS_PAYMENTS.OBJECT_VERSION_ID IS 'Optimistic locking version number'
/
