SET DEFINE OFF;
CREATE TABLE DEMASYLABS.POS_PRODUCTS_PROMOTIONS
(
  PROMOTION_ID       NUMBER CONSTRAINT PPP_PROMOTION_ID_NNC NOT NULL,
  PROMO_CODE         VARCHAR2(60 CHAR) CONSTRAINT PPP_PROMO_CODE_NNC NOT NULL,
  NAME               VARCHAR2(300 BYTE) CONSTRAINT PPP_NAME_NNC NOT NULL,
  DESCRIPTION        VARCHAR2(4000 CHAR),
  STATUS_CODE        VARCHAR2(30 CHAR)          DEFAULT 'A' CONSTRAINT PPP_STATUS_CODE_NNC NOT NULL,
  ENABLED_FLAG       VARCHAR2(1 CHAR)           DEFAULT 'Y' CONSTRAINT PPP_ENABLED_FLAG_NNC NOT NULL,
  START_DATE         DATE                       DEFAULT sysdate CONSTRAINT PPP_START_DATE_NNC NOT NULL,
  END_DATE           DATE,
  CREATED_BY         NUMBER CONSTRAINT PPP_CREATED_BY_NNC NOT NULL,
  CREATION_DATE      DATE CONSTRAINT PPP_CREATION_DATE_NNC NOT NULL,
  LAST_UPDATED_BY    NUMBER CONSTRAINT PPP_LAST_UPDATED_BY_NNC NOT NULL,
  LAST_UPDATE_DATE   DATE CONSTRAINT PPP_LAST_UPDATE_DATE_NNC NOT NULL,
  OBJECT_VERSION_ID  NUMBER CONSTRAINT PPP_OBJECT_VERSION_ID_NNC NOT NULL,
  CONSTRAINT PPP_ENABLED_FLAG_CK
  CHECK ( enabled_flag IN ( 'N', 'Y' ) )
  ENABLE VALIDATE
,  CONSTRAINT PPP_STATUS_CODE_CK
  CHECK ( status_code IN ( 'A', 'D', 'I', 'P' ) )
  ENABLE VALIDATE
,  CONSTRAINT PPP_PROMOTION_ID_PK
  PRIMARY KEY
  (PROMOTION_ID)
  ENABLE VALIDATE
,  CONSTRAINT PPP_NAME_UN
  UNIQUE (NAME)
  ENABLE VALIDATE
,  CONSTRAINT PPP_PROMO_CODE_UN
  UNIQUE (PROMO_CODE)
  ENABLE VALIDATE
)
LOGGING 
NOCOMPRESS 
NO INMEMORY
NOCACHE
RESULT_CACHE (MODE DEFAULT)
NOPARALLEL
/

COMMENT ON TABLE DEMASYLABS.POS_PRODUCTS_PROMOTIONS IS 'Product promotions and discount campaigns for point-of-sale system. Manages promotional offers, discount codes, and marketing campaigns with usage tracking and validation rules.'
/

COMMENT ON COLUMN DEMASYLABS.POS_PRODUCTS_PROMOTIONS.PROMOTION_ID IS 'Unique promotion identifier (Primary Key)'
/

COMMENT ON COLUMN DEMASYLABS.POS_PRODUCTS_PROMOTIONS.PROMO_CODE IS 'Unique promotional code for customer use'
/

COMMENT ON COLUMN DEMASYLABS.POS_PRODUCTS_PROMOTIONS.NAME IS 'Promotion campaign name for internal reference'
/

COMMENT ON COLUMN DEMASYLABS.POS_PRODUCTS_PROMOTIONS.DESCRIPTION IS 'Detailed promotion description and terms'
/

COMMENT ON COLUMN DEMASYLABS.POS_PRODUCTS_PROMOTIONS.STATUS_CODE IS 'Product operational status: A=Active, I=Inactive, D=Discontinued, P=Pending'
/

COMMENT ON COLUMN DEMASYLABS.POS_PRODUCTS_PROMOTIONS.ENABLED_FLAG IS 'Active status flag (Y/N)'
/

COMMENT ON COLUMN DEMASYLABS.POS_PRODUCTS_PROMOTIONS.START_DATE IS 'Effective start date'
/

COMMENT ON COLUMN DEMASYLABS.POS_PRODUCTS_PROMOTIONS.END_DATE IS 'Effective end date'
/

COMMENT ON COLUMN DEMASYLABS.POS_PRODUCTS_PROMOTIONS.CREATED_BY IS 'User who created the record'
/

COMMENT ON COLUMN DEMASYLABS.POS_PRODUCTS_PROMOTIONS.CREATION_DATE IS 'Record creation timestamp'
/

COMMENT ON COLUMN DEMASYLABS.POS_PRODUCTS_PROMOTIONS.LAST_UPDATED_BY IS 'User who last updated the record'
/

COMMENT ON COLUMN DEMASYLABS.POS_PRODUCTS_PROMOTIONS.LAST_UPDATE_DATE IS 'Last update timestamp'
/

COMMENT ON COLUMN DEMASYLABS.POS_PRODUCTS_PROMOTIONS.OBJECT_VERSION_ID IS 'Optimistic locking version number'
/
