SET DEFINE OFF;
CREATE TABLE DEMASYLABS.POS_PRODUCTS
(
  PRODUCT_ID         NUMBER CONSTRAINT PP_PRODUCT_ID_NNC NOT NULL,
  SUB_CATEGORY_ID    NUMBER CONSTRAINT PP_SUB_CATEGORY_ID_NNC NOT NULL,
  PRODUCT_CODE       VARCHAR2(30 CHAR) CONSTRAINT PP_PRODUCT_CODE_NNC NOT NULL,
  PRODUCT_NAME       VARCHAR2(200 CHAR) CONSTRAINT PP_PRODUCT_NAME_NNC NOT NULL,
  SHORT_DESCRIPTION  VARCHAR2(500 BYTE),
  LONG_DESCRIPTION   VARCHAR2(4000 BYTE),
  MANUFACTURER_CODE  VARCHAR2(30 CHAR) CONSTRAINT PP_MANUFACTURER_CODE_NNC NOT NULL,
  BAR_CODE           VARCHAR2(30 CHAR),
  BRAND_CODE         VARCHAR2(30 CHAR) CONSTRAINT PP_BRAND_CODE_NNC NOT NULL,
  MODEL_NUMBER       VARCHAR2(100 CHAR) CONSTRAINT PP_MODEL_NUMBER_NNC NOT NULL,
  REFERENCE_NUMBER   VARCHAR2(30 CHAR),
  PRICE              NUMBER(7,3) CONSTRAINT PP_PRICE_NNC NOT NULL,
  CURRENCY_CODE      VARCHAR2(30 CHAR) CONSTRAINT PP_CURRENCY_CODE_NNC NOT NULL,
  CAPACITY           NUMBER,
  LENGTH             NUMBER,
  HEIGHT             NUMBER,
  WIDTH              NUMBER,
  STATUS_CODE        VARCHAR2(30 CHAR)          DEFAULT 'A' CONSTRAINT PP_STATUS_CODE_NNC NOT NULL,
  ENABLED_FLAG       VARCHAR2(1 CHAR)           DEFAULT 'Y' CONSTRAINT PP_ENABLED_FLAG_NNC NOT NULL,
  START_DATE         DATE                       DEFAULT sysdate CONSTRAINT PP_START_DATE_NNC NOT NULL,
  END_DATE           DATE,
  CREATED_BY         NUMBER CONSTRAINT PP_CREATED_BY_NNC NOT NULL,
  CREATION_DATE      DATE CONSTRAINT PP_CREATION_DATE_NNC NOT NULL,
  LAST_UPDATED_BY    NUMBER CONSTRAINT PP_LAST_UPDATED_BY_NNC NOT NULL,
  LAST_UPDATE_DATE   DATE CONSTRAINT PP_LAST_UPDATE_DATE_NNC NOT NULL,
  OBJECT_VERSION_ID  NUMBER CONSTRAINT PP_OBJECT_VERSION_ID_NNC NOT NULL,
  CONSTRAINT PP_ENABLED_FLAG_CK
  CHECK ( enabled_flag IN ( 'N', 'Y' ) )
  ENABLE VALIDATE
,  CONSTRAINT PP_STATUS_CODE_CK
  CHECK ( status_code IN ( 'A', 'D', 'I', 'P' ) )
  ENABLE VALIDATE
,  CONSTRAINT PP_PRODUCT_ID_PK
  PRIMARY KEY
  (PRODUCT_ID)
  ENABLE VALIDATE
,  CONSTRAINT PP_SUB_CATEGORY_ID_FK 
  FOREIGN KEY (SUB_CATEGORY_ID) 
  REFERENCES DEMASYLABS.POS_PRODUCT_SUB_CATEGORIES (SUB_CATEGORY_ID)
  ENABLE VALIDATE
,  CONSTRAINT PP_BAR_CODE_UN
  UNIQUE (BAR_CODE)
  ENABLE VALIDATE
,  CONSTRAINT PP_PRODUCT_CODE_UN
  UNIQUE (PRODUCT_CODE)
  ENABLE VALIDATE
,  CONSTRAINT PP_PRODUCT_NAME_UN
  UNIQUE (PRODUCT_NAME)
  ENABLE VALIDATE
,  CONSTRAINT PP_REFERENCE_NUMBER_UN
  UNIQUE (REFERENCE_NUMBER)
  ENABLE VALIDATE
)
LOGGING 
NOCOMPRESS 
NO INMEMORY
NOCACHE
RESULT_CACHE (MODE DEFAULT)
NOPARALLEL
/

COMMENT ON TABLE DEMASYLABS.POS_PRODUCTS IS 'Product master table containing comprehensive product information for the POS system. Stores all product details including pricing, dimensions, and categorization for retail operations and inventory management.'
/

COMMENT ON COLUMN DEMASYLABS.POS_PRODUCTS.PRODUCT_ID IS 'Primary identifier for products'
/

COMMENT ON COLUMN DEMASYLABS.POS_PRODUCTS.SUB_CATEGORY_ID IS 'Foreign key reference to product sub-category for classification'
/

COMMENT ON COLUMN DEMASYLABS.POS_PRODUCTS.PRODUCT_CODE IS 'Unique business product code/SKU for inventory tracking'
/

COMMENT ON COLUMN DEMASYLABS.POS_PRODUCTS.PRODUCT_NAME IS 'Product name for customer displays and documentation'
/

COMMENT ON COLUMN DEMASYLABS.POS_PRODUCTS.SHORT_DESCRIPTION IS 'Brief product description for compact displays and reports'
/

COMMENT ON COLUMN DEMASYLABS.POS_PRODUCTS.LONG_DESCRIPTION IS 'Detailed product description with specifications and features'
/

COMMENT ON COLUMN DEMASYLABS.POS_PRODUCTS.MANUFACTURER_CODE IS 'Manufacturer code/identifier for supplier management'
/

COMMENT ON COLUMN DEMASYLABS.POS_PRODUCTS.BAR_CODE IS 'Product barcode (UPC/EAN) for point-of-sale scanning'
/

COMMENT ON COLUMN DEMASYLABS.POS_PRODUCTS.BRAND_CODE IS 'Brand code for product brand classification and reporting'
/

COMMENT ON COLUMN DEMASYLABS.POS_PRODUCTS.MODEL_NUMBER IS 'Manufacturer model number or product variant identifier'
/

COMMENT ON COLUMN DEMASYLABS.POS_PRODUCTS.REFERENCE_NUMBER IS 'Manufacturer part number or reference code'
/

COMMENT ON COLUMN DEMASYLABS.POS_PRODUCTS.PRICE IS 'Retail selling price for customer transactions'
/

COMMENT ON COLUMN DEMASYLABS.POS_PRODUCTS.CURRENCY_CODE IS 'ISO 3-letter currency code for price denomination'
/

COMMENT ON COLUMN DEMASYLABS.POS_PRODUCTS.CAPACITY IS 'Product capacity (volume, memory, quantity, etc.)'
/

COMMENT ON COLUMN DEMASYLABS.POS_PRODUCTS.LENGTH IS 'Product length dimension for shipping and storage'
/

COMMENT ON COLUMN DEMASYLABS.POS_PRODUCTS.HEIGHT IS 'Product height dimension for shipping and storage'
/

COMMENT ON COLUMN DEMASYLABS.POS_PRODUCTS.WIDTH IS 'Product width dimension for shipping and storage'
/

COMMENT ON COLUMN DEMASYLABS.POS_PRODUCTS.STATUS_CODE IS 'Product operational status: A=Active, I=Inactive, D=Discontinued, P=Pending'
/

COMMENT ON COLUMN DEMASYLABS.POS_PRODUCTS.ENABLED_FLAG IS 'Active status flag (Y/N)'
/

COMMENT ON COLUMN DEMASYLABS.POS_PRODUCTS.START_DATE IS 'Effective start date'
/

COMMENT ON COLUMN DEMASYLABS.POS_PRODUCTS.END_DATE IS 'Effective end date'
/

COMMENT ON COLUMN DEMASYLABS.POS_PRODUCTS.CREATED_BY IS 'User who created the record'
/

COMMENT ON COLUMN DEMASYLABS.POS_PRODUCTS.CREATION_DATE IS 'Record creation timestamp'
/

COMMENT ON COLUMN DEMASYLABS.POS_PRODUCTS.LAST_UPDATED_BY IS 'User who last updated the record'
/

COMMENT ON COLUMN DEMASYLABS.POS_PRODUCTS.LAST_UPDATE_DATE IS 'Last update timestamp'
/

COMMENT ON COLUMN DEMASYLABS.POS_PRODUCTS.OBJECT_VERSION_ID IS 'Optimistic locking version number'
/
