SET DEFINE OFF;
CREATE TABLE DEMASYLABS.POS_STORES
(
  STORE_ID           NUMBER(10) CONSTRAINT PS_STORE_ID_NNC NOT NULL,
  COUNTRY_CODE       VARCHAR2(3 CHAR) CONSTRAINT PS_COUNTRY_CODE_NNC NOT NULL,
  SHORT_NAME         VARCHAR2(50 CHAR) CONSTRAINT PS_SHORT_NAME_NNC NOT NULL,
  NAME               VARCHAR2(100 CHAR) CONSTRAINT PS_NAME_NNC NOT NULL,
  DESCRIPTION        VARCHAR2(4000 CHAR),
  STATUS_CODE        VARCHAR2(30 CHAR)          DEFAULT 'A' CONSTRAINT PS_STATUS_CODE_NNC NOT NULL,
  ENABLED_FLAG       VARCHAR2(1 CHAR)           DEFAULT 'Y' CONSTRAINT PS_ENABLED_FLAG_NNC NOT NULL,
  START_DATE         DATE                       DEFAULT sysdate CONSTRAINT PS_START_DATE_NNC NOT NULL,
  END_DATE           DATE,
  CREATED_BY         NUMBER CONSTRAINT PS_CREATED_BY_NNC NOT NULL,
  CREATION_DATE      DATE CONSTRAINT PS_CREATION_DATE_NNC NOT NULL,
  LAST_UPDATED_BY    NUMBER CONSTRAINT PS_LAST_UPDATED_BY_NNC NOT NULL,
  LAST_UPDATE_DATE   DATE CONSTRAINT PS_LAST_UPDATE_DATE_NNC NOT NULL,
  OBJECT_VERSION_ID  NUMBER CONSTRAINT PS_OBJECT_VERSION_ID_NNC NOT NULL,
  CONSTRAINT PS_ENABLED_FLAG_CK
  CHECK ( enabled_flag IN ( 'N', 'Y' ) )
  ENABLE VALIDATE
,  CONSTRAINT PS_STATUS_CODE_CK
  CHECK ( status_code IN ( 'A', 'I' ) )
  ENABLE VALIDATE
,  CONSTRAINT PS_STORE_ID_PK
  PRIMARY KEY
  (STORE_ID)
  ENABLE VALIDATE
,  CONSTRAINT PS_NAME_UN
  UNIQUE (NAME)
  ENABLE VALIDATE
,  CONSTRAINT PS_SHORT_NAME_UN
  UNIQUE (SHORT_NAME)
  ENABLE VALIDATE
)
LOGGING 
NOCOMPRESS 
NO INMEMORY
NOCACHE
RESULT_CACHE (MODE DEFAULT)
NOPARALLEL
/

COMMENT ON TABLE DEMASYLABS.POS_STORES IS 'Master store table for managing retail locations. Stores represent top-level business units that can contain multiple branches for operational hierarchy and reporting.'
/

COMMENT ON COLUMN DEMASYLABS.POS_STORES.STORE_ID IS 'Primary identifier for stores'
/

COMMENT ON COLUMN DEMASYLABS.POS_STORES.COUNTRY_CODE IS 'ISO country code (2-3 characters) for store location'
/

COMMENT ON COLUMN DEMASYLABS.POS_STORES.SHORT_NAME IS 'Abbreviated store name for reports and displays'
/

COMMENT ON COLUMN DEMASYLABS.POS_STORES.NAME IS 'Full store name for official documentation'
/

COMMENT ON COLUMN DEMASYLABS.POS_STORES.DESCRIPTION IS 'Store details, location notes, and operational information'
/

COMMENT ON COLUMN DEMASYLABS.POS_STORES.STATUS_CODE IS 'Store operational status: A=Active, I=Inactive'
/

COMMENT ON COLUMN DEMASYLABS.POS_STORES.ENABLED_FLAG IS 'Active status'
/

COMMENT ON COLUMN DEMASYLABS.POS_STORES.START_DATE IS 'Effective start date'
/

COMMENT ON COLUMN DEMASYLABS.POS_STORES.END_DATE IS 'Effective end date'
/

COMMENT ON COLUMN DEMASYLABS.POS_STORES.CREATED_BY IS 'User who created the record'
/

COMMENT ON COLUMN DEMASYLABS.POS_STORES.CREATION_DATE IS 'Record creation timestamp'
/

COMMENT ON COLUMN DEMASYLABS.POS_STORES.LAST_UPDATED_BY IS 'User who last updated the record'
/

COMMENT ON COLUMN DEMASYLABS.POS_STORES.LAST_UPDATE_DATE IS 'Last update timestamp'
/

COMMENT ON COLUMN DEMASYLABS.POS_STORES.OBJECT_VERSION_ID IS 'Optimistic locking version number'
/
