SET DEFINE OFF;
CREATE TABLE DEMASYLABS.POS_PRODUCT_TRANSACTIONS
(
  TRANSACTION_ID     NUMBER CONSTRAINT PPT_TRANSACTION_ID_NNC NOT NULL,
  WAREHOUSE_ID       NUMBER CONSTRAINT PPT_WAREHOUSE_ID_NNC NOT NULL,
  PRODUCT_ID         NUMBER CONSTRAINT PPT_PRODUCT_ID_NNC NOT NULL,
  TRX_TYPE           VARCHAR2(30 CHAR) CONSTRAINT PPT_TRX_TYPE_NNC NOT NULL,
  TRX_NUMBER         VARCHAR2(100 CHAR) CONSTRAINT PPT_TRX_NUMBER_NNC NOT NULL,
  DESCRIPTION        VARCHAR2(4000 CHAR),
  QUANTITY           NUMBER(7,3),
  UNIT_COST          NUMBER(7,2),
  PROCESSED_FLAG     VARCHAR2(1 CHAR),
  CANCEL_FLAG        VARCHAR2(1 CHAR),
  CANCELED_BY        NUMBER,
  CANCEL_REASON      VARCHAR2(1000 CHAR),
  STATUS_CODE        VARCHAR2(30 CHAR)          DEFAULT 'A' CONSTRAINT PPT_STATUS_CODE_NNC NOT NULL,
  ENABLED_FLAG       VARCHAR2(1 CHAR)           DEFAULT 'Y' CONSTRAINT PPT_ENABLED_FLAG_NNC NOT NULL,
  START_DATE         DATE                       DEFAULT sysdate CONSTRAINT PPT_START_DATE_NNC NOT NULL,
  END_DATE           DATE,
  CREATED_BY         NUMBER CONSTRAINT PPT_CREATED_BY_NNC NOT NULL,
  CREATION_DATE      DATE CONSTRAINT PPT_CREATION_DATE_NNC NOT NULL,
  LAST_UPDATED_BY    NUMBER CONSTRAINT PPT_LAST_UPDATED_BY_NNC NOT NULL,
  LAST_UPDATE_DATE   DATE CONSTRAINT PPT_LAST_UPDATE_DATE_NNC NOT NULL,
  OBJECT_VERSION_ID  NUMBER CONSTRAINT PPT_OBJECT_VERSION_ID_NNC NOT NULL,
  CONSTRAINT PPT_CANCEL_FLAG_CK
  CHECK ( cancel_flag IN ( 'N', 'Y' ) )
  ENABLE VALIDATE
,  CONSTRAINT PPT_ENABLED_FLAG_CK
  CHECK ( enabled_flag IN ( 'N', 'Y' ) )
  ENABLE VALIDATE
,  CONSTRAINT PPT_PROCESSED_FLAG_CK
  CHECK ( processed_flag IN ( 'N', 'Y' ) )
  ENABLE VALIDATE
,  CONSTRAINT PPT_STATUS_CODE_CK
  CHECK ( status_code IN ( 'A', 'D', 'I', 'P' ) )
  ENABLE VALIDATE
,  CONSTRAINT PPT_TRX_TYPE_CK
  CHECK ( trx_type IN ( 'AIN', 'AOU', 'CCT', 'DMG', 'ISS',
                              'PCT', 'RCP', 'RFD', 'RTN', 'SAL',
                              'TIN', 'TOU' ) )
  ENABLE VALIDATE
,  CONSTRAINT PPT_TRANSACTION_ID_PK
  PRIMARY KEY
  (TRANSACTION_ID)
  ENABLE VALIDATE
,  CONSTRAINT PPT_PRODUCT_ID_FK 
  FOREIGN KEY (PRODUCT_ID) 
  REFERENCES DEMASYLABS.POS_PRODUCTS (PRODUCT_ID)
  ENABLE VALIDATE
,  CONSTRAINT PPT_WAREHOUSE_ID_FK 
  FOREIGN KEY (WAREHOUSE_ID) 
  REFERENCES DEMASYLABS.POS_WAREHOUSES (WAREHOUSE_ID)
  ENABLE VALIDATE
,  CONSTRAINT PPT_TRX_NUMBER_UN
  UNIQUE (TRX_NUMBER)
  ENABLE VALIDATE
)
LOGGING 
NOCOMPRESS 
NO INMEMORY
NOCACHE
RESULT_CACHE (MODE DEFAULT)
NOPARALLEL
/

COMMENT ON TABLE DEMASYLABS.POS_PRODUCT_TRANSACTIONS IS 'Product inventory transactions tracking all stock movements including receipts, issues, transfers, adjustments, sales, and returns. Supports complete audit trail and cancellation workflow.'
/

COMMENT ON COLUMN DEMASYLABS.POS_PRODUCT_TRANSACTIONS.TRANSACTION_ID IS 'Unique transaction identifier (Primary Key)'
/

COMMENT ON COLUMN DEMASYLABS.POS_PRODUCT_TRANSACTIONS.WAREHOUSE_ID IS 'Warehouse where transaction occurred (FK to pos_warehouses)'
/

COMMENT ON COLUMN DEMASYLABS.POS_PRODUCT_TRANSACTIONS.PRODUCT_ID IS 'Product being transacted (FK to pos_products)'
/

COMMENT ON COLUMN DEMASYLABS.POS_PRODUCT_TRANSACTIONS.TRX_TYPE IS 'Transaction type: RECEIPT, ISSUE, TRANSFER_IN, TRANSFER_OUT, ADJUSTMENT_IN, ADJUSTMENT_OUT, RETURN, DAMAGE, CYCLE_COUNT, PHYSICAL_COUNT, SALE, REFUND'
/

COMMENT ON COLUMN DEMASYLABS.POS_PRODUCT_TRANSACTIONS.TRX_NUMBER IS 'Human-readable transaction reference number'
/

COMMENT ON COLUMN DEMASYLABS.POS_PRODUCT_TRANSACTIONS.DESCRIPTION IS 'Detailed transaction description or notes'
/

COMMENT ON COLUMN DEMASYLABS.POS_PRODUCT_TRANSACTIONS.QUANTITY IS 'Transaction quantity (positive for increases, negative for decreases)'
/

COMMENT ON COLUMN DEMASYLABS.POS_PRODUCT_TRANSACTIONS.UNIT_COST IS 'Cost per unit for valuation purposes'
/

COMMENT ON COLUMN DEMASYLABS.POS_PRODUCT_TRANSACTIONS.PROCESSED_FLAG IS 'Processing completion flag (Y/N)'
/

COMMENT ON COLUMN DEMASYLABS.POS_PRODUCT_TRANSACTIONS.CANCEL_FLAG IS 'Transaction cancellation flag (Y/N)'
/

COMMENT ON COLUMN DEMASYLABS.POS_PRODUCT_TRANSACTIONS.CANCELED_BY IS 'User who canceled the transaction'
/

COMMENT ON COLUMN DEMASYLABS.POS_PRODUCT_TRANSACTIONS.CANCEL_REASON IS 'Reason for transaction cancellation'
/

COMMENT ON COLUMN DEMASYLABS.POS_PRODUCT_TRANSACTIONS.STATUS_CODE IS 'Product operational status: A=Active, I=Inactive, D=Discontinued, P=Pending'
/

COMMENT ON COLUMN DEMASYLABS.POS_PRODUCT_TRANSACTIONS.ENABLED_FLAG IS 'Active status flag (Y/N)'
/

COMMENT ON COLUMN DEMASYLABS.POS_PRODUCT_TRANSACTIONS.START_DATE IS 'Effective start date'
/

COMMENT ON COLUMN DEMASYLABS.POS_PRODUCT_TRANSACTIONS.END_DATE IS 'Effective end date'
/

COMMENT ON COLUMN DEMASYLABS.POS_PRODUCT_TRANSACTIONS.CREATED_BY IS 'User who created the record'
/

COMMENT ON COLUMN DEMASYLABS.POS_PRODUCT_TRANSACTIONS.CREATION_DATE IS 'Record creation timestamp'
/

COMMENT ON COLUMN DEMASYLABS.POS_PRODUCT_TRANSACTIONS.LAST_UPDATED_BY IS 'User who last updated the record'
/

COMMENT ON COLUMN DEMASYLABS.POS_PRODUCT_TRANSACTIONS.LAST_UPDATE_DATE IS 'Last update timestamp'
/

COMMENT ON COLUMN DEMASYLABS.POS_PRODUCT_TRANSACTIONS.OBJECT_VERSION_ID IS 'Optimistic locking version number'
/
