SET DEFINE OFF;
CREATE TABLE DEMASYLABS.POS_PARTIES
(
  PARTY_ID             NUMBER CONSTRAINT PPS_PARTY_ID_NNC NOT NULL,
  PARTY_TYPE           VARCHAR2(1 CHAR) CONSTRAINT PPS_PARTY_TYPE_NNC NOT NULL,
  PARTY_NUMBER         VARCHAR2(30 BYTE) CONSTRAINT PPS_PARTY_NUMBER_NNC NOT NULL,
  PARTY_NAME           VARCHAR2(360 CHAR) CONSTRAINT PPS_PARTY_NAME_NNC NOT NULL,
  DESCRIPTION          VARCHAR2(4000 BYTE),
  TITLE_CODE           VARCHAR2(30 CHAR),
  FIRST_NAME           VARCHAR2(100 CHAR),
  MIDDLE_NAME          VARCHAR2(100 CHAR),
  LAST_NAME            VARCHAR2(100 CHAR),
  NICKNAME             VARCHAR2(100 CHAR),
  GENDER_CODE          VARCHAR2(1 CHAR),
  MARITAL_STATUS_CODE  VARCHAR2(1 CHAR),
  BIRTH_DATE           DATE,
  HOLD_FLAG            VARCHAR2(1 CHAR)         DEFAULT 'N',
  STATUS_CODE          VARCHAR2(30 CHAR)        DEFAULT 'A' CONSTRAINT PPS_STATUS_CODE_NNC NOT NULL,
  ENABLED_FLAG         VARCHAR2(1 CHAR)         DEFAULT 'Y' CONSTRAINT PPS_ENABLED_FLAG_NNC NOT NULL,
  START_DATE           DATE                     DEFAULT sysdate CONSTRAINT PPS_START_DATE_NNC NOT NULL,
  END_DATE             DATE,
  CREATED_BY           NUMBER CONSTRAINT PPS_CREATED_BY_NNC NOT NULL,
  CREATION_DATE        DATE CONSTRAINT PPS_CREATION_DATE_NNC NOT NULL,
  LAST_UPDATED_BY      NUMBER CONSTRAINT PPS_LAST_UPDATED_BY_NNC NOT NULL,
  LAST_UPDATE_DATE     DATE CONSTRAINT PPS_LAST_UPDATE_DATE_NNC NOT NULL,
  OBJECT_VERSION_ID    NUMBER CONSTRAINT PPS_OBJECT_VERSION_ID_NNC NOT NULL,
  CONSTRAINT PPS_ENABLED_FLAG_CK
  CHECK ( enabled_flag IN ( 'N', 'Y' ) )
  ENABLE VALIDATE
,  CONSTRAINT PPS_GENDER_CODE_CK
  CHECK ( gender_code IN ( 'F', 'M', 'N', 'O' ) )
  ENABLE VALIDATE
,  CONSTRAINT PPS_HOLD_FLAG_CK
  CHECK ( hold_flag IN ( 'N', 'Y' ) )
  ENABLE VALIDATE
,  CONSTRAINT PPS_MARITAL_STATUS_CODE_CK
  CHECK ( marital_status_code IN ( 'D', 'M', 'S', 'W' ) )
  ENABLE VALIDATE
,  CONSTRAINT PPS_PARTY_TYPE_CK
  CHECK ( party_type IN ( 'E', 'G', 'O', 'P' ) )
  ENABLE VALIDATE
,  CONSTRAINT PPS_STATUS_CODE_CK
  CHECK ( status_code IN ( 'A', 'B', 'I', 'P', 'S' ) )
  ENABLE VALIDATE
,  CONSTRAINT PPS_PARTY_ID_PK
  PRIMARY KEY
  (PARTY_ID)
  ENABLE VALIDATE
,  CONSTRAINT PPS_PARTY_NUMBER_UN
  UNIQUE (PARTY_NUMBER)
  ENABLE VALIDATE
)
LOGGING 
NOCOMPRESS 
NO INMEMORY
NOCACHE
RESULT_CACHE (MODE DEFAULT)
NOPARALLEL
/

COMMENT ON TABLE DEMASYLABS.POS_PARTIES IS 'Master party table implementing the Party Pattern design. Stores unified data for all entities (persons, organizations) including customers, vendors, employees, and suppliers. Serves as the foundation for relationship management across the POS system.'
/

COMMENT ON COLUMN DEMASYLABS.POS_PARTIES.PARTY_ID IS 'Primary identifier for parties (persons/organizations)'
/

COMMENT ON COLUMN DEMASYLABS.POS_PARTIES.PARTY_TYPE IS 'Party type: P=Person, O=Organization, E=Employee, G=Group'
/

COMMENT ON COLUMN DEMASYLABS.POS_PARTIES.PARTY_NUMBER IS 'Business-friendly unique identifier'
/

COMMENT ON COLUMN DEMASYLABS.POS_PARTIES.PARTY_NAME IS 'Computed full name: title + first + middle + last for persons, party_name for others'
/

COMMENT ON COLUMN DEMASYLABS.POS_PARTIES.DESCRIPTION IS 'Additional notes or description'
/

COMMENT ON COLUMN DEMASYLABS.POS_PARTIES.TITLE_CODE IS 'Personal title (Mr, Ms, Mrs, Dr, Prof, etc.) - applicable for person type parties'
/

COMMENT ON COLUMN DEMASYLABS.POS_PARTIES.FIRST_NAME IS 'First name for person type parties'
/

COMMENT ON COLUMN DEMASYLABS.POS_PARTIES.MIDDLE_NAME IS 'Middle name for person type parties'
/

COMMENT ON COLUMN DEMASYLABS.POS_PARTIES.LAST_NAME IS 'Last name for person type parties'
/

COMMENT ON COLUMN DEMASYLABS.POS_PARTIES.NICKNAME IS 'Preferred name or nickname'
/

COMMENT ON COLUMN DEMASYLABS.POS_PARTIES.GENDER_CODE IS 'Gender: M=Male, F=Female, O=Other, N=Not specified'
/

COMMENT ON COLUMN DEMASYLABS.POS_PARTIES.MARITAL_STATUS_CODE IS 'Marital status (S/M/D/W for Single/Married/Divorced/Widowed)'
/

COMMENT ON COLUMN DEMASYLABS.POS_PARTIES.BIRTH_DATE IS 'Birth date for person type parties'
/

COMMENT ON COLUMN DEMASYLABS.POS_PARTIES.HOLD_FLAG IS 'Temporary hold status (Y/N)'
/

COMMENT ON COLUMN DEMASYLABS.POS_PARTIES.STATUS_CODE IS 'Status: A=Active, B=Blocked, I=Inactive, P=Pending, S=Suspended'
/

COMMENT ON COLUMN DEMASYLABS.POS_PARTIES.ENABLED_FLAG IS 'Active status (Y/N)'
/

COMMENT ON COLUMN DEMASYLABS.POS_PARTIES.START_DATE IS 'Effective start date'
/

COMMENT ON COLUMN DEMASYLABS.POS_PARTIES.END_DATE IS 'Effective end date'
/

COMMENT ON COLUMN DEMASYLABS.POS_PARTIES.CREATED_BY IS 'User who created the record'
/

COMMENT ON COLUMN DEMASYLABS.POS_PARTIES.CREATION_DATE IS 'Record creation timestamp'
/

COMMENT ON COLUMN DEMASYLABS.POS_PARTIES.LAST_UPDATED_BY IS 'User who last updated the record'
/

COMMENT ON COLUMN DEMASYLABS.POS_PARTIES.LAST_UPDATE_DATE IS 'Last update timestamp'
/

COMMENT ON COLUMN DEMASYLABS.POS_PARTIES.OBJECT_VERSION_ID IS 'Optimistic locking version number'
/
