SET DEFINE OFF;
CREATE TABLE DEMASYLABS.POS_CUSTOMERS
(
  CUSTOMER_ID          NUMBER CONSTRAINT PC_CUSTOMER_ID_NNC NOT NULL,
  PARTY_ID             NUMBER CONSTRAINT PC_PARTY_ID_NNC NOT NULL,
  SOURCE_CODE          VARCHAR2(30 CHAR) CONSTRAINT PC_SOURCE_CODE_NNC NOT NULL,
  TYPE_CODE            VARCHAR2(30 CHAR) CONSTRAINT PC_TYPE_CODE_NNC NOT NULL,
  CUSTOMER_NUMBER      VARCHAR2(30 BYTE) CONSTRAINT PC_CUSTOMER_NUMBER_NNC NOT NULL,
  REGISTERED_DATE      DATE,
  IDENTIFIER_TYPE      VARCHAR2(1 CHAR),
  IDENTIFIER_NUMBER    VARCHAR2(100 CHAR),
  PREF_CONTACT_CODE    VARCHAR2(30 CHAR),
  MOBILE_NUMBER        VARCHAR2(30 CHAR) CONSTRAINT PC_MOBILE_NUMBER_NNC NOT NULL,
  PHONE_NUMBER         VARCHAR2(30 CHAR),
  EMAIL_ADDRESS        VARCHAR2(200 CHAR),
  ADDRESS              VARCHAR2(4000 BYTE),
  PAY_TERMS_CODE       VARCHAR2(30 CHAR),
  CREDIT_LIMIT         NUMBER(13,2),
  CURRENT_BALANCE      NUMBER(13,2),
  LOGIN_USER           VARCHAR2(20 CHAR),
  LOGIN_PASSWORD       VARCHAR2(30 CHAR),
  PASSWORD_HASH        VARCHAR2(128 CHAR),
  PASSWORD_SALT        VARCHAR2(64 CHAR),
  LAST_PASS_CHANGE     DATE,
  CHILD_UNDER_18_FLAG  VARCHAR2(1 CHAR),
  HOLD_FLAG            VARCHAR2(1 CHAR)         DEFAULT 'N',
  LOCKED_FLAG          VARCHAR2(1 CHAR)         DEFAULT 'N',
  DESCRIPTION          VARCHAR2(4000 BYTE),
  STATUS_CODE          VARCHAR2(30 CHAR)        DEFAULT 'A' CONSTRAINT PC_STATUS_CODE_NNC NOT NULL,
  ENABLED_FLAG         VARCHAR2(1 CHAR)         DEFAULT 'Y' CONSTRAINT PC_ENABLED_FLAG_NNC NOT NULL,
  START_DATE           DATE                     DEFAULT sysdate CONSTRAINT PC_START_DATE_NNC NOT NULL,
  END_DATE             DATE,
  CREATED_BY           NUMBER CONSTRAINT PC_CREATED_BY_NNC NOT NULL,
  CREATION_DATE        DATE CONSTRAINT PC_CREATION_DATE_NNC NOT NULL,
  LAST_UPDATED_BY      NUMBER CONSTRAINT PC_LAST_UPDATED_BY_NNC NOT NULL,
  LAST_UPDATE_DATE     DATE CONSTRAINT PC_LAST_UPDATE_DATE_NNC NOT NULL,
  OBJECT_VERSION_ID    NUMBER CONSTRAINT PC_OBJECT_VERSION_ID_NNC NOT NULL,
  CONSTRAINT PC_ENABLED_FLAG_CK
  CHECK ( enabled_flag IN ( 'N', 'Y' ) )
  ENABLE VALIDATE
,  CONSTRAINT PC_HOLD_FLAG_CK
  CHECK ( hold_flag IN ( 'N', 'Y' ) )
  ENABLE VALIDATE
,  CONSTRAINT PC_IDENTIFIER_TYPE_CK
  CHECK ( identifier_type IN ( 'D', 'L', 'P' ) )
  ENABLE VALIDATE
,  CONSTRAINT PC_LOCKED_FLAG_CK
  CHECK ( locked_flag IN ( 'N', 'Y' ) )
  ENABLE VALIDATE
,  CONSTRAINT PC_PAY_TERMS_CODE_CK
  CHECK ( pay_terms_code IN ( 'C', 'CR' ) )
  ENABLE VALIDATE
,  CONSTRAINT PC_PREF_CONTACT_CODE_CK
  CHECK ( pref_contact_code IN ( 'E', 'M', 'P' ) )
  ENABLE VALIDATE
,  CONSTRAINT PC_SOURCE_CODE_CK
  CHECK ( source_code IN ( 'A', 'M' ) )
  ENABLE VALIDATE
,  CONSTRAINT PC_STATUS_CODE_CK
  CHECK ( status_code IN ( 'A', 'B', 'I', 'S' ) )
  ENABLE VALIDATE
,  CONSTRAINT PC_TYPE_CODE_CK
  CHECK ( type_code IN ( 'C', 'R', 'V', 'W' ) )
  ENABLE VALIDATE
,  CONSTRAINT PC_CUSTOMER_ID_PK
  PRIMARY KEY
  (CUSTOMER_ID)
  ENABLE VALIDATE
,  CONSTRAINT PC_PARTY_ID_FK 
  FOREIGN KEY (PARTY_ID) 
  REFERENCES DEMASYLABS.POS_PARTIES (PARTY_ID)
  ENABLE VALIDATE
,  CONSTRAINT PC_CUSTOMER_NUMBER_UN
  UNIQUE (CUSTOMER_NUMBER)
  ENABLE VALIDATE
,  CONSTRAINT PC_LOGIN_USER_UN
  UNIQUE (LOGIN_USER)
  ENABLE VALIDATE
,  CONSTRAINT PC_MOBILE_NUMBER_UN
  UNIQUE (MOBILE_NUMBER)
  ENABLE VALIDATE
)
LOGGING 
NOCOMPRESS 
NO INMEMORY
NOCACHE
RESULT_CACHE (MODE DEFAULT)
NOPARALLEL
/

COMMENT ON TABLE DEMASYLABS.POS_CUSTOMERS IS 'Customer master table storing comprehensive customer information, preferences, financial data, and relationship management for Point-of-Sale system operations.'
/

COMMENT ON COLUMN DEMASYLABS.POS_CUSTOMERS.CUSTOMER_ID IS 'Primary identifier for customers'
/

COMMENT ON COLUMN DEMASYLABS.POS_CUSTOMERS.PARTY_ID IS 'Foreign key reference to POS_PARTIES'
/

COMMENT ON COLUMN DEMASYLABS.POS_CUSTOMERS.SOURCE_CODE IS 'Customer acquisition source'
/

COMMENT ON COLUMN DEMASYLABS.POS_CUSTOMERS.TYPE_CODE IS 'Customer classification type'
/

COMMENT ON COLUMN DEMASYLABS.POS_CUSTOMERS.CUSTOMER_NUMBER IS 'Business-friendly customer identifier'
/

COMMENT ON COLUMN DEMASYLABS.POS_CUSTOMERS.REGISTERED_DATE IS 'Customer registration date'
/

COMMENT ON COLUMN DEMASYLABS.POS_CUSTOMERS.IDENTIFIER_TYPE IS 'ID document type'
/

COMMENT ON COLUMN DEMASYLABS.POS_CUSTOMERS.IDENTIFIER_NUMBER IS 'ID document number'
/

COMMENT ON COLUMN DEMASYLABS.POS_CUSTOMERS.PREF_CONTACT_CODE IS 'Preferred contact method'
/

COMMENT ON COLUMN DEMASYLABS.POS_CUSTOMERS.MOBILE_NUMBER IS 'Primary mobile contact'
/

COMMENT ON COLUMN DEMASYLABS.POS_CUSTOMERS.PHONE_NUMBER IS 'Secondary phone contact'
/

COMMENT ON COLUMN DEMASYLABS.POS_CUSTOMERS.EMAIL_ADDRESS IS 'Email address'
/

COMMENT ON COLUMN DEMASYLABS.POS_CUSTOMERS.ADDRESS IS 'Primary address'
/

COMMENT ON COLUMN DEMASYLABS.POS_CUSTOMERS.PAY_TERMS_CODE IS 'Payment terms code'
/

COMMENT ON COLUMN DEMASYLABS.POS_CUSTOMERS.CREDIT_LIMIT IS 'Customer credit limit amount'
/

COMMENT ON COLUMN DEMASYLABS.POS_CUSTOMERS.CURRENT_BALANCE IS 'Current outstanding balance'
/

COMMENT ON COLUMN DEMASYLABS.POS_CUSTOMERS.LOGIN_USER IS 'Customer portal username'
/

COMMENT ON COLUMN DEMASYLABS.POS_CUSTOMERS.LOGIN_PASSWORD IS 'Customer portal password'
/

COMMENT ON COLUMN DEMASYLABS.POS_CUSTOMERS.PASSWORD_HASH IS 'Hashed customer portal password using bcrypt or SHA-256'
/

COMMENT ON COLUMN DEMASYLABS.POS_CUSTOMERS.PASSWORD_SALT IS 'Salt value used for password hashing to prevent rainbow table attacks'
/

COMMENT ON COLUMN DEMASYLABS.POS_CUSTOMERS.LAST_PASS_CHANGE IS 'Timestamp of last password change for security policy enforcement'
/

COMMENT ON COLUMN DEMASYLABS.POS_CUSTOMERS.CHILD_UNDER_18_FLAG IS 'Has children under 18 flag'
/

COMMENT ON COLUMN DEMASYLABS.POS_CUSTOMERS.HOLD_FLAG IS 'Temporary hold status'
/

COMMENT ON COLUMN DEMASYLABS.POS_CUSTOMERS.LOCKED_FLAG IS 'Account locked status'
/

COMMENT ON COLUMN DEMASYLABS.POS_CUSTOMERS.DESCRIPTION IS 'Customer-specific notes and comments'
/

COMMENT ON COLUMN DEMASYLABS.POS_CUSTOMERS.STATUS_CODE IS 'Current customer status'
/

COMMENT ON COLUMN DEMASYLABS.POS_CUSTOMERS.ENABLED_FLAG IS 'Active status'
/

COMMENT ON COLUMN DEMASYLABS.POS_CUSTOMERS.START_DATE IS 'Effective start date'
/

COMMENT ON COLUMN DEMASYLABS.POS_CUSTOMERS.END_DATE IS 'Effective end date'
/

COMMENT ON COLUMN DEMASYLABS.POS_CUSTOMERS.CREATED_BY IS 'User who created the record'
/

COMMENT ON COLUMN DEMASYLABS.POS_CUSTOMERS.CREATION_DATE IS 'Record creation timestamp'
/

COMMENT ON COLUMN DEMASYLABS.POS_CUSTOMERS.LAST_UPDATED_BY IS 'User who last updated the record'
/

COMMENT ON COLUMN DEMASYLABS.POS_CUSTOMERS.LAST_UPDATE_DATE IS 'Last update timestamp'
/

COMMENT ON COLUMN DEMASYLABS.POS_CUSTOMERS.OBJECT_VERSION_ID IS 'Optimistic locking version number'
/
