SET DEFINE OFF;
CREATE TABLE DEMASYLABS.POS_PRODUCTS_PROMO_DETAILS
(
  PROMO_DETAIL_ID    NUMBER CONSTRAINT PPPD_PROMO_DETAIL_ID_NNC NOT NULL,
  PRODUCT_ID         NUMBER CONSTRAINT PPPD_PRODUCT_ID_NNC NOT NULL,
  PROMOTION_ID       NUMBER CONSTRAINT PPPD_PROMOTION_ID_NNC NOT NULL,
  DISCOUNT_TYPE      VARCHAR2(30 CHAR) CONSTRAINT PPPD_DISCOUNT_TYPE_NNC NOT NULL,
  PRIORITY_ORDER     NUMBER,
  PERCENTAGE         NUMBER(5,2),
  FIXED_AMOUNT       NUMBER(10,2),
  STATUS_CODE        VARCHAR2(30 CHAR)          DEFAULT 'A' CONSTRAINT PPPD_STATUS_CODE_NNC NOT NULL,
  ENABLED_FLAG       VARCHAR2(1 CHAR)           DEFAULT 'Y' CONSTRAINT PPPD_ENABLED_FLAG_NNC NOT NULL,
  START_DATE         DATE                       DEFAULT sysdate CONSTRAINT PPPD_START_DATE_NNC NOT NULL,
  END_DATE           DATE,
  CREATED_BY         NUMBER CONSTRAINT PPPD_CREATED_BY_NNC NOT NULL,
  CREATION_DATE      DATE CONSTRAINT PPPD_CREATION_DATE_NNC NOT NULL,
  LAST_UPDATED_BY    NUMBER CONSTRAINT PPPD_LAST_UPDATED_BY_NNC NOT NULL,
  LAST_UPDATE_DATE   DATE CONSTRAINT PPPD_LAST_UPDATE_DATE_NNC NOT NULL,
  OBJECT_VERSION_ID  NUMBER CONSTRAINT PPPD_OBJECT_VERSION_ID_NNC NOT NULL,
  CONSTRAINT PPPD_DISCOUNT_TYPE_CK
  CHECK ( discount_type IN ( 'BXGY', 'FA', 'FS', 'P' ) )
  ENABLE VALIDATE
,  CONSTRAINT PPPD_ENABLED_FLAG_CK
  CHECK ( enabled_flag IN ( 'N', 'Y' ) )
  ENABLE VALIDATE
,  CONSTRAINT PPPD_STATUS_CODE_CK
  CHECK ( status_code IN ( 'A', 'D', 'I', 'P' ) )
  ENABLE VALIDATE
,  CONSTRAINT PPPD_PROMO_DETAIL_ID_PK
  PRIMARY KEY
  (PROMO_DETAIL_ID)
  ENABLE VALIDATE
,  CONSTRAINT PPPD_PRODUCT_ID_FK 
  FOREIGN KEY (PRODUCT_ID) 
  REFERENCES DEMASYLABS.POS_PRODUCTS (PRODUCT_ID)
  ENABLE VALIDATE
,  CONSTRAINT PPPD_PROMOTION_ID_FK 
  FOREIGN KEY (PROMOTION_ID) 
  REFERENCES DEMASYLABS.POS_PRODUCTS_PROMOTIONS (PROMOTION_ID)
  ENABLE VALIDATE
)
LOGGING 
NOCOMPRESS 
NO INMEMORY
NOCACHE
RESULT_CACHE (MODE DEFAULT)
NOPARALLEL
/

COMMENT ON TABLE DEMASYLABS.POS_PRODUCTS_PROMO_DETAILS IS 'Product-promotion relationship details. Junction table linking specific products to promotional campaigns, enabling targeted discounts and marketing offers on individual products.'
/

COMMENT ON COLUMN DEMASYLABS.POS_PRODUCTS_PROMO_DETAILS.PROMO_DETAIL_ID IS 'Unique product-promotion relationship identifier (Primary Key)'
/

COMMENT ON COLUMN DEMASYLABS.POS_PRODUCTS_PROMO_DETAILS.PRODUCT_ID IS 'Product identifier (Foreign Key to pos_products)'
/

COMMENT ON COLUMN DEMASYLABS.POS_PRODUCTS_PROMO_DETAILS.PROMOTION_ID IS 'Promotion identifier (Foreign Key to pos_products_promotions)'
/

COMMENT ON COLUMN DEMASYLABS.POS_PRODUCTS_PROMO_DETAILS.DISCOUNT_TYPE IS 'Discount type: P=Percentage, FA=Fixed Amount, BXGY=Buy X Get Y, FS=Free Shipping'
/

COMMENT ON COLUMN DEMASYLABS.POS_PRODUCTS_PROMO_DETAILS.PRIORITY_ORDER IS 'Promotion priority order (lower numbers = higher priority)'
/

COMMENT ON COLUMN DEMASYLABS.POS_PRODUCTS_PROMO_DETAILS.PERCENTAGE IS 'Percentage discount (0-100) when discount_type is PERCENTAGE'
/

COMMENT ON COLUMN DEMASYLABS.POS_PRODUCTS_PROMO_DETAILS.FIXED_AMOUNT IS 'Fixed discount amount when discount_type is FIXED_AMOUNT'
/

COMMENT ON COLUMN DEMASYLABS.POS_PRODUCTS_PROMO_DETAILS.STATUS_CODE IS 'Product operational status: A=Active, I=Inactive, D=Discontinued, P=Pending'
/

COMMENT ON COLUMN DEMASYLABS.POS_PRODUCTS_PROMO_DETAILS.ENABLED_FLAG IS 'Active status flag (Y/N)'
/

COMMENT ON COLUMN DEMASYLABS.POS_PRODUCTS_PROMO_DETAILS.START_DATE IS 'Effective start date'
/

COMMENT ON COLUMN DEMASYLABS.POS_PRODUCTS_PROMO_DETAILS.END_DATE IS 'Effective end date'
/

COMMENT ON COLUMN DEMASYLABS.POS_PRODUCTS_PROMO_DETAILS.CREATED_BY IS 'User who created the record'
/

COMMENT ON COLUMN DEMASYLABS.POS_PRODUCTS_PROMO_DETAILS.CREATION_DATE IS 'Record creation timestamp'
/

COMMENT ON COLUMN DEMASYLABS.POS_PRODUCTS_PROMO_DETAILS.LAST_UPDATED_BY IS 'User who last updated the record'
/

COMMENT ON COLUMN DEMASYLABS.POS_PRODUCTS_PROMO_DETAILS.LAST_UPDATE_DATE IS 'Last update timestamp'
/

COMMENT ON COLUMN DEMASYLABS.POS_PRODUCTS_PROMO_DETAILS.OBJECT_VERSION_ID IS 'Optimistic locking version number'
/
