SET DEFINE OFF;
CREATE TABLE DEMASYLABS.POS_CASHIERS
(
  CASHIER_ID            NUMBER CONSTRAINT PCA_CASHIER_ID_NNC NOT NULL,
  PARTY_ID              NUMBER CONSTRAINT PCA_PARTY_ID_NNC NOT NULL,
  SUPERVISOR_ID         NUMBER,
  CASHIER_TYPE          VARCHAR2(1 CHAR) CONSTRAINT PCA_CASHIER_TYPE_NNC NOT NULL,
  CASHIER_NUMBER        NUMBER,
  DESCRIPTION           VARCHAR2(4000 CHAR),
  HOLD_FLAG             VARCHAR2(1 CHAR)        DEFAULT 'N',
  LOGIN_USER            VARCHAR2(20 CHAR),
  LOGIN_PASSWORD        VARCHAR2(30 CHAR),
  PASSWORD_HASH         VARCHAR2(128 CHAR),
  PASSWORD_SALT         VARCHAR2(64 CHAR),
  LAST_PASSWORD_CHANGE  TIMESTAMP(6),
  STATUS_CODE           VARCHAR2(30 CHAR)       DEFAULT 'A' CONSTRAINT PCA_STATUS_CODE_NNC NOT NULL,
  ENABLED_FLAG          VARCHAR2(1 CHAR)        DEFAULT 'Y' CONSTRAINT PCA_ENABLED_FLAG_NNC NOT NULL,
  START_DATE            DATE                    DEFAULT sysdate CONSTRAINT PCA_START_DATE_NNC NOT NULL,
  END_DATE              DATE,
  CREATED_BY            NUMBER CONSTRAINT PCA_CREATED_BY_NNC NOT NULL,
  CREATION_DATE         DATE CONSTRAINT PCA_CREATION_DATE_NNC NOT NULL,
  LAST_UPDATED_BY       NUMBER CONSTRAINT PCA_LAST_UPDATED_BY_NNC NOT NULL,
  LAST_UPDATE_DATE      DATE CONSTRAINT PCA_LAST_UPDATE_DATE_NNC NOT NULL,
  OBJECT_VERSION_ID     NUMBER CONSTRAINT PCA_OBJECT_VERSION_ID_NNC NOT NULL,
  CONSTRAINT PCA_CASHIER_TYPE_CK
  CHECK ( cashier_type IN ( 'A', 'M', 'R', 'S', 'SV' ) )
  ENABLE VALIDATE
,  CONSTRAINT PCA_ENABLED_FLAG_CK
  CHECK ( enabled_flag IN ( 'N', 'Y' ) )
  ENABLE VALIDATE
,  CONSTRAINT PCA_HOLD_FLAG_CK
  CHECK ( hold_flag IN ( 'N', 'Y' ) )
  ENABLE VALIDATE
,  CONSTRAINT PCA_STATUS_CODE_CK
  CHECK ( status_code IN ( 'A', 'B', 'I', 'P', 'S' ) )
  ENABLE VALIDATE
,  CONSTRAINT PCA_CASHIER_ID_PK
  PRIMARY KEY
  (CASHIER_ID)
  ENABLE VALIDATE
,  CONSTRAINT PCA_CASHIER_ID_FK 
  FOREIGN KEY (SUPERVISOR_ID) 
  REFERENCES DEMASYLABS.POS_CASHIERS (CASHIER_ID)
  ENABLE VALIDATE
,  CONSTRAINT PCA_PARTY_ID_FK 
  FOREIGN KEY (PARTY_ID) 
  REFERENCES DEMASYLABS.POS_PARTIES (PARTY_ID)
  ENABLE VALIDATE
,  CONSTRAINT PCA_CASHIER_NUMBER_UN
  UNIQUE (CASHIER_NUMBER)
  ENABLE VALIDATE
,  CONSTRAINT PCA_LOGIN_USER_UN
  UNIQUE (LOGIN_USER)
  ENABLE VALIDATE
)
LOGGING 
NOCOMPRESS 
NO INMEMORY
NOCACHE
RESULT_CACHE (MODE DEFAULT)
NOPARALLEL
/

COMMENT ON TABLE DEMASYLABS.POS_CASHIERS IS 'Cashier and employee management table for POS system access control. Stores authentication credentials, role assignments, and operational permissions for staff members. Integrates with pos_parties for unified employee data management.'
/

COMMENT ON COLUMN DEMASYLABS.POS_CASHIERS.CASHIER_ID IS 'Primary identifier for cashiers'
/

COMMENT ON COLUMN DEMASYLABS.POS_CASHIERS.PARTY_ID IS 'Foreign key reference to pos_parties table for employee personal information'
/

COMMENT ON COLUMN DEMASYLABS.POS_CASHIERS.SUPERVISOR_ID IS 'Reference to supervising cashier/manager for hierarchical reporting structure'
/

COMMENT ON COLUMN DEMASYLABS.POS_CASHIERS.CASHIER_TYPE IS 'Cashier role type: A=Admin, M=Manager, R=Regular, S=Supervisor, SV=Supervisor (alternate)'
/

COMMENT ON COLUMN DEMASYLABS.POS_CASHIERS.CASHIER_NUMBER IS 'Employee/cashier number'
/

COMMENT ON COLUMN DEMASYLABS.POS_CASHIERS.DESCRIPTION IS 'Cashier-specific notes'
/

COMMENT ON COLUMN DEMASYLABS.POS_CASHIERS.HOLD_FLAG IS 'Temporary hold status (Y/N)'
/

COMMENT ON COLUMN DEMASYLABS.POS_CASHIERS.LOGIN_USER IS 'System login username for POS access'
/

COMMENT ON COLUMN DEMASYLABS.POS_CASHIERS.LOGIN_PASSWORD IS 'Legacy password field - use password_hash for secure storage'
/

COMMENT ON COLUMN DEMASYLABS.POS_CASHIERS.PASSWORD_HASH IS 'Hashed login password using bcrypt or SHA-256 algorithm'
/

COMMENT ON COLUMN DEMASYLABS.POS_CASHIERS.PASSWORD_SALT IS 'Salt value for password hashing security'
/

COMMENT ON COLUMN DEMASYLABS.POS_CASHIERS.LAST_PASSWORD_CHANGE IS 'Timestamp of last password change for policy enforcement'
/

COMMENT ON COLUMN DEMASYLABS.POS_CASHIERS.STATUS_CODE IS 'A=Active, B=Blocked, I=Inactive, P=Pending, S=Suspended'
/

COMMENT ON COLUMN DEMASYLABS.POS_CASHIERS.ENABLED_FLAG IS 'Active status (Y/N)'
/

COMMENT ON COLUMN DEMASYLABS.POS_CASHIERS.START_DATE IS 'Effective start date'
/

COMMENT ON COLUMN DEMASYLABS.POS_CASHIERS.END_DATE IS 'Effective end date'
/

COMMENT ON COLUMN DEMASYLABS.POS_CASHIERS.CREATED_BY IS 'User who created the record'
/

COMMENT ON COLUMN DEMASYLABS.POS_CASHIERS.CREATION_DATE IS 'Record creation timestamp'
/

COMMENT ON COLUMN DEMASYLABS.POS_CASHIERS.LAST_UPDATED_BY IS 'User who last updated the record'
/

COMMENT ON COLUMN DEMASYLABS.POS_CASHIERS.LAST_UPDATE_DATE IS 'Last update timestamp'
/

COMMENT ON COLUMN DEMASYLABS.POS_CASHIERS.OBJECT_VERSION_ID IS 'Optimistic locking version number'
/
