SET DEFINE OFF;
CREATE TABLE DEMASYLABS.POS_INVOICES
(
  INVOICE_ID         NUMBER CONSTRAINT PI_INVOICE_ID_NNC NOT NULL,
  ORDER_ID           NUMBER CONSTRAINT PI_ORDER_ID_NNC NOT NULL,
  PROMOTION_ID       NUMBER,
  INVOICE_NUMBER     VARCHAR2(30 CHAR) CONSTRAINT PI_INVOICE_NUMBER_NNC NOT NULL,
  DESCRIPTION        VARCHAR2(4000 CHAR),
  AMOUNT             NUMBER(15,2) CONSTRAINT PI_AMOUNT_NNC NOT NULL,
  CURRENCY_CODE      VARCHAR2(3 CHAR) CONSTRAINT PI_CURRENCY_CODE_NNC NOT NULL,
  STATUS_CODE        VARCHAR2(30 CHAR)          DEFAULT 'A' CONSTRAINT PI_STATUS_CODE_NNC NOT NULL,
  ENABLED_FLAG       VARCHAR2(1 CHAR)           DEFAULT 'Y' CONSTRAINT PI_ENABLED_FLAG_NNC NOT NULL,
  START_DATE         DATE                       DEFAULT sysdate CONSTRAINT PI_START_DATE_NNC NOT NULL,
  END_DATE           DATE,
  CREATED_BY         NUMBER CONSTRAINT PI_CREATED_BY_NNC NOT NULL,
  CREATION_DATE      DATE CONSTRAINT PI_CREATION_DATE_NNC NOT NULL,
  LAST_UPDATED_BY    NUMBER CONSTRAINT PI_LAST_UPDATED_BY_NNC NOT NULL,
  LAST_UPDATE_DATE   DATE CONSTRAINT PI_LAST_UPDATE_DATE_NNC NOT NULL,
  OBJECT_VERSION_ID  NUMBER CONSTRAINT PI_OBJECT_VERSION_ID_NNC NOT NULL,
  CONSTRAINT PI_CURRENCY_CODE_CK
  CHECK ( currency_code IN ( 'AUD', 'CAD', 'EGP', 'EUR', 'GBP',
                                   'JPY', 'SAR', 'USD' ) )
  ENABLE VALIDATE
,  CONSTRAINT PI_ENABLED_FLAG_CK
  CHECK ( enabled_flag IN ( 'N', 'Y' ) )
  ENABLE VALIDATE
,  CONSTRAINT PI_STATUS_CODE_CK
  CHECK ( status_code IN ( 'A', 'C', 'P', 'R', 'V' ) )
  ENABLE VALIDATE
,  CONSTRAINT PI_INVOICE_ID_PK
  PRIMARY KEY
  (INVOICE_ID)
  ENABLE VALIDATE
,  CONSTRAINT PI_ORDER_ID_FK 
  FOREIGN KEY (ORDER_ID) 
  REFERENCES DEMASYLABS.POS_ORDERS (ORDER_ID)
  ENABLE VALIDATE
,  CONSTRAINT PI_PROMOTION_ID_FK 
  FOREIGN KEY (PROMOTION_ID) 
  REFERENCES DEMASYLABS.POS_PRODUCTS_PROMOTIONS (PROMOTION_ID)
  ENABLE VALIDATE
,  CONSTRAINT PI_INVOICE_NUMBER_UN
  UNIQUE (INVOICE_NUMBER)
  ENABLE VALIDATE
)
LOGGING 
NOCOMPRESS 
NO INMEMORY
NOCACHE
RESULT_CACHE (MODE DEFAULT)
NOPARALLEL
/

COMMENT ON TABLE DEMASYLABS.POS_INVOICES IS 'Invoice records for point-of-sale orders. Manages billing information, amounts, and invoice lifecycle for financial processing and customer billing.'
/

COMMENT ON COLUMN DEMASYLABS.POS_INVOICES.INVOICE_ID IS 'Unique invoice identifier (Primary Key)'
/

COMMENT ON COLUMN DEMASYLABS.POS_INVOICES.ORDER_ID IS 'Associated order identifier (Foreign Key to pos_orders)'
/

COMMENT ON COLUMN DEMASYLABS.POS_INVOICES.PROMOTION_ID IS 'Applied promotion identifier (Foreign Key to pos_products_promotions)'
/

COMMENT ON COLUMN DEMASYLABS.POS_INVOICES.INVOICE_NUMBER IS 'Unique invoice reference number for customer billing'
/

COMMENT ON COLUMN DEMASYLABS.POS_INVOICES.DESCRIPTION IS 'Invoice description and billing details'
/

COMMENT ON COLUMN DEMASYLABS.POS_INVOICES.AMOUNT IS 'Total invoice amount in specified currency'
/

COMMENT ON COLUMN DEMASYLABS.POS_INVOICES.CURRENCY_CODE IS 'Payment currency code (ISO 4217 standard)'
/

COMMENT ON COLUMN DEMASYLABS.POS_INVOICES.STATUS_CODE IS 'Invoice status: A=Approved, C=Cancelled, P=Pending, R=Refunded, V=Void'
/

COMMENT ON COLUMN DEMASYLABS.POS_INVOICES.ENABLED_FLAG IS 'Active status flag (Y/N)'
/

COMMENT ON COLUMN DEMASYLABS.POS_INVOICES.START_DATE IS 'Effective start date'
/

COMMENT ON COLUMN DEMASYLABS.POS_INVOICES.END_DATE IS 'Effective end date'
/

COMMENT ON COLUMN DEMASYLABS.POS_INVOICES.CREATED_BY IS 'User who created the record'
/

COMMENT ON COLUMN DEMASYLABS.POS_INVOICES.CREATION_DATE IS 'Record creation timestamp'
/

COMMENT ON COLUMN DEMASYLABS.POS_INVOICES.LAST_UPDATED_BY IS 'User who last updated the record'
/

COMMENT ON COLUMN DEMASYLABS.POS_INVOICES.LAST_UPDATE_DATE IS 'Last update timestamp'
/

COMMENT ON COLUMN DEMASYLABS.POS_INVOICES.OBJECT_VERSION_ID IS 'Optimistic locking version number'
/
