SET DEFINE OFF;
CREATE TABLE DEMASYLABS.POS_STORE_BRANCHES
(
  BRANCH_ID          NUMBER(10) CONSTRAINT PSB_BRANCH_ID_NNC NOT NULL,
  STORE_ID           NUMBER(10) CONSTRAINT PSB_STORE_ID_NNC NOT NULL,
  PARENT_ID          NUMBER(10),
  SHORT_NAME         VARCHAR2(50 CHAR) CONSTRAINT PSB_SHORT_NAME_NNC NOT NULL,
  NAME               VARCHAR2(100 CHAR) CONSTRAINT PSB_NAME_NNC NOT NULL,
  DESCRIPTION        VARCHAR2(4000 BYTE),
  MANAGER_ID         NUMBER(10) CONSTRAINT PSB_MANAGER_ID_NNC NOT NULL,
  STATUS_CODE        VARCHAR2(30 CHAR)          DEFAULT 'A' CONSTRAINT PSB_STATUS_CODE_NNC NOT NULL,
  ENABLED_FLAG       VARCHAR2(1 CHAR)           DEFAULT 'Y' CONSTRAINT PSB_ENABLED_FLAG_NNC NOT NULL,
  START_DATE         DATE                       DEFAULT sysdate CONSTRAINT PSB_START_DATE_NNC NOT NULL,
  END_DATE           DATE,
  CREATED_BY         NUMBER CONSTRAINT PSB_CREATED_BY_NNC NOT NULL,
  CREATION_DATE      DATE CONSTRAINT PSB_CREATION_DATE_NNC NOT NULL,
  LAST_UPDATED_BY    NUMBER CONSTRAINT PSB_LAST_UPDATED_BY_NNC NOT NULL,
  LAST_UPDATE_DATE   DATE CONSTRAINT PSB_LAST_UPDATE_DATE_NNC NOT NULL,
  OBJECT_VERSION_ID  NUMBER CONSTRAINT PSB_OBJECT_VERSION_ID_NNC NOT NULL,
  CONSTRAINT PSB_ENABLED_FLAG_CK
  CHECK ( enabled_flag IN ( 'N', 'Y' ) )
  ENABLE VALIDATE
,  CONSTRAINT PSB_STATUS_CODE_CK
  CHECK ( status_code IN ( 'A', 'B', 'I', 'S' ) )
  ENABLE VALIDATE
,  CONSTRAINT PSB_BRANCH_ID_PK
  PRIMARY KEY
  (BRANCH_ID)
  ENABLE VALIDATE
,  CONSTRAINT PSB_CASHIER_ID_FK 
  FOREIGN KEY (MANAGER_ID) 
  REFERENCES DEMASYLABS.POS_CASHIERS (CASHIER_ID)
  ENABLE VALIDATE
,  CONSTRAINT PSB_STORE_ID_FK 
  FOREIGN KEY (STORE_ID) 
  REFERENCES DEMASYLABS.POS_STORES (STORE_ID)
  ENABLE VALIDATE
,  CONSTRAINT PSB_NAME_UN
  UNIQUE (NAME)
  ENABLE VALIDATE
,  CONSTRAINT PSB_SHORT_NAME_UN
  UNIQUE (SHORT_NAME)
  ENABLE VALIDATE
)
LOGGING 
NOCOMPRESS 
NO INMEMORY
NOCACHE
RESULT_CACHE (MODE DEFAULT)
NOPARALLEL
/

COMMENT ON TABLE DEMASYLABS.POS_STORE_BRANCHES IS 'Branch management table for store subdivisions. Branches represent operational units within stores, supporting hierarchical organization with parent-child relationships and manager assignments.'
/

COMMENT ON COLUMN DEMASYLABS.POS_STORE_BRANCHES.BRANCH_ID IS 'Primary identifier for branches'
/

COMMENT ON COLUMN DEMASYLABS.POS_STORE_BRANCHES.STORE_ID IS 'Foreign key reference to parent store'
/

COMMENT ON COLUMN DEMASYLABS.POS_STORE_BRANCHES.PARENT_ID IS 'Self-referencing foreign key for branch hierarchy (sub-branches)'
/

COMMENT ON COLUMN DEMASYLABS.POS_STORE_BRANCHES.SHORT_NAME IS 'Abbreviated branch name for reports and displays'
/

COMMENT ON COLUMN DEMASYLABS.POS_STORE_BRANCHES.NAME IS 'Full branch name for official documentation'
/

COMMENT ON COLUMN DEMASYLABS.POS_STORE_BRANCHES.DESCRIPTION IS 'Branch details, location notes, and operational information'
/

COMMENT ON COLUMN DEMASYLABS.POS_STORE_BRANCHES.MANAGER_ID IS 'Reference to branch manager (pos_cashiers table)'
/

COMMENT ON COLUMN DEMASYLABS.POS_STORE_BRANCHES.STATUS_CODE IS 'Branch operational status: A=Active, B=Blocked, I=Inactive, S=Suspended'
/

COMMENT ON COLUMN DEMASYLABS.POS_STORE_BRANCHES.ENABLED_FLAG IS 'Active status'
/

COMMENT ON COLUMN DEMASYLABS.POS_STORE_BRANCHES.START_DATE IS 'Effective start date'
/

COMMENT ON COLUMN DEMASYLABS.POS_STORE_BRANCHES.END_DATE IS 'Effective end date'
/

COMMENT ON COLUMN DEMASYLABS.POS_STORE_BRANCHES.CREATED_BY IS 'User who created the record'
/

COMMENT ON COLUMN DEMASYLABS.POS_STORE_BRANCHES.CREATION_DATE IS 'Record creation timestamp'
/

COMMENT ON COLUMN DEMASYLABS.POS_STORE_BRANCHES.LAST_UPDATED_BY IS 'User who last updated the record'
/

COMMENT ON COLUMN DEMASYLABS.POS_STORE_BRANCHES.LAST_UPDATE_DATE IS 'Last update timestamp'
/

COMMENT ON COLUMN DEMASYLABS.POS_STORE_BRANCHES.OBJECT_VERSION_ID IS 'Optimistic locking version number'
/
