SET DEFINE OFF;
CREATE TABLE DEMASYLABS.POS_WAREHOUSES
(
  WAREHOUSE_ID       NUMBER CONSTRAINT PW_WAREHOUSE_ID_NNC NOT NULL,
  BRANCH_ID          NUMBER(10) CONSTRAINT PW_BRANCH_ID_NNC NOT NULL,
  PARENT_ID          NUMBER(10),
  WAREHOUSE_TYPE     VARCHAR2(30 CHAR) CONSTRAINT PW_WAREHOUSE_TYPE_NNC NOT NULL,
  SHORT_NAME         VARCHAR2(30 CHAR) CONSTRAINT PW_SHORT_NAME_NNC NOT NULL,
  NAME               VARCHAR2(100 CHAR) CONSTRAINT PW_NAME_NNC NOT NULL,
  DESCRIPTION        VARCHAR2(4000 BYTE),
  ADDRESS_LINE1      VARCHAR2(1000 BYTE) CONSTRAINT PW_ADDRESS_LINE1_NNC NOT NULL,
  ADDRESS_LINE2      VARCHAR2(1000 BYTE) CONSTRAINT PW_ADDRESS_LINE2_NNC NOT NULL,
  COUNTRY_CODE       VARCHAR2(30 CHAR) CONSTRAINT PW_COUNTRY_CODE_NNC NOT NULL,
  CITY               VARCHAR2(30 CHAR) CONSTRAINT PW_CITY_NNC NOT NULL,
  STATE_PROVINCE     VARCHAR2(30 CHAR) CONSTRAINT PW_STATE_PROVINCE_NNC NOT NULL,
  POSTAL_CODE        VARCHAR2(30 CHAR) CONSTRAINT PW_POSTAL_CODE_NNC NOT NULL,
  PHONE_NUMBER       VARCHAR2(50 BYTE) CONSTRAINT PW_PHONE_NUMBER_NNC NOT NULL,
  EMAIL_ADDRESS      VARCHAR2(100 BYTE) CONSTRAINT PW_EMAIL_ADDRESS_NNC NOT NULL,
  CAPACITY_SQFT      NUMBER(10,2),
  MAX_CAPACITY       NUMBER(10),
  STATUS_CODE        VARCHAR2(30 CHAR)          DEFAULT 'A' CONSTRAINT PW_STATUS_CODE_NNC NOT NULL,
  ENABLED_FLAG       VARCHAR2(1 CHAR)           DEFAULT 'Y' CONSTRAINT PW_ENABLED_FLAG_NNC NOT NULL,
  START_DATE         DATE                       DEFAULT sysdate CONSTRAINT PW_START_DATE_NNC NOT NULL,
  END_DATE           DATE,
  CREATED_BY         NUMBER CONSTRAINT PW_CREATED_BY_NNC NOT NULL,
  CREATION_DATE      DATE CONSTRAINT PW_CREATION_DATE_NNC NOT NULL,
  LAST_UPDATED_BY    NUMBER CONSTRAINT PW_LAST_UPDATED_BY_NNC NOT NULL,
  LAST_UPDATE_DATE   DATE CONSTRAINT PW_LAST_UPDATE_DATE_NNC NOT NULL,
  OBJECT_VERSION_ID  NUMBER CONSTRAINT PW_OBJECT_VERSION_ID_NNC NOT NULL,
  CONSTRAINT PW_ENABLED_FLAG_CK
  CHECK ( enabled_flag IN ( 'N', 'Y' ) )
  ENABLE VALIDATE
,  CONSTRAINT PW_STATUS_CODE_CK
  CHECK ( status_code IN ( 'A', 'D', 'I', 'P' ) )
  ENABLE VALIDATE
,  CONSTRAINT PW_WAREHOUSE_TYPE_CK
  CHECK ( warehouse_type IN ( 'B', 'CS', 'M', 'OF', 'S' ) )
  ENABLE VALIDATE
,  CONSTRAINT PW_WAREHOUSE_ID_PK
  PRIMARY KEY
  (WAREHOUSE_ID)
  ENABLE VALIDATE
,  CONSTRAINT PW_BRANCH_ID_FK 
  FOREIGN KEY (BRANCH_ID) 
  REFERENCES DEMASYLABS.POS_STORE_BRANCHES (BRANCH_ID)
  ENABLE VALIDATE
,  CONSTRAINT PW_NAME_UN
  UNIQUE (NAME)
  ENABLE VALIDATE
,  CONSTRAINT PW_SHORT_NAME_UN
  UNIQUE (SHORT_NAME)
  ENABLE VALIDATE
)
LOGGING 
NOCOMPRESS 
NO INMEMORY
NOCACHE
RESULT_CACHE (MODE DEFAULT)
NOPARALLEL
/

COMMENT ON TABLE DEMASYLABS.POS_WAREHOUSES IS 'Warehouse facilities management within store branch hierarchy. Supports multi-level warehouse organization with capacity tracking and comprehensive address information.'
/

COMMENT ON COLUMN DEMASYLABS.POS_WAREHOUSES.WAREHOUSE_ID IS 'Unique warehouse identifier (Primary Key)'
/

COMMENT ON COLUMN DEMASYLABS.POS_WAREHOUSES.PARENT_ID IS 'Parent warehouse ID for hierarchical organization (Self FK)'
/

COMMENT ON COLUMN DEMASYLABS.POS_WAREHOUSES.WAREHOUSE_TYPE IS 'Warehouse classification: M=Main, B=Backup, OF=Overflow, CS=Cold Storage, S=Staging'
/

COMMENT ON COLUMN DEMASYLABS.POS_WAREHOUSES.CAPACITY_SQFT IS 'Warehouse floor area capacity in square feet'
/

COMMENT ON COLUMN DEMASYLABS.POS_WAREHOUSES.MAX_CAPACITY IS 'Maximum storage capacity (units/pallets/containers)'
/

COMMENT ON COLUMN DEMASYLABS.POS_WAREHOUSES.STATUS_CODE IS 'Product operational status: A=Active, I=Inactive, D=Discontinued, P=Pending'
/

COMMENT ON COLUMN DEMASYLABS.POS_WAREHOUSES.ENABLED_FLAG IS 'Active status flag (Y/N)'
/

COMMENT ON COLUMN DEMASYLABS.POS_WAREHOUSES.START_DATE IS 'Effective start date'
/

COMMENT ON COLUMN DEMASYLABS.POS_WAREHOUSES.END_DATE IS 'Effective end date'
/

COMMENT ON COLUMN DEMASYLABS.POS_WAREHOUSES.CREATED_BY IS 'User who created the record'
/

COMMENT ON COLUMN DEMASYLABS.POS_WAREHOUSES.CREATION_DATE IS 'Record creation timestamp'
/

COMMENT ON COLUMN DEMASYLABS.POS_WAREHOUSES.LAST_UPDATED_BY IS 'User who last updated the record'
/

COMMENT ON COLUMN DEMASYLABS.POS_WAREHOUSES.LAST_UPDATE_DATE IS 'Last update timestamp'
/

COMMENT ON COLUMN DEMASYLABS.POS_WAREHOUSES.OBJECT_VERSION_ID IS 'Optimistic locking version number'
/
