SET DEFINE OFF;
CREATE TABLE DEMASYLABS.POS_PRODUCT_SUB_CATEGORIES
(
  SUB_CATEGORY_ID    NUMBER CONSTRAINT PPSC_SUB_CATEGORY_ID_NNC NOT NULL,
  CATEGORY_ID        NUMBER CONSTRAINT PPSC_CATEGORY_ID_NNC NOT NULL,
  DISPLAY_ORDER      NUMBER CONSTRAINT PPSC_DISPLAY_ORDER_NNC NOT NULL,
  SHORT_NAME         VARCHAR2(50 CHAR) CONSTRAINT PPSC_SHORT_NAME_NNC NOT NULL,
  NAME               VARCHAR2(200 CHAR) CONSTRAINT PPSC_NAME_NNC NOT NULL,
  DESCRIPTION        VARCHAR2(4000 CHAR),
  STATUS_CODE        VARCHAR2(30 CHAR)          DEFAULT 'A' CONSTRAINT PPSC_STATUS_CODE_NNC NOT NULL,
  ENABLED_FLAG       VARCHAR2(1 CHAR)           DEFAULT 'Y' CONSTRAINT PPSC_ENABLED_FLAG_NNC NOT NULL,
  START_DATE         DATE                       DEFAULT sysdate CONSTRAINT PPSC_START_DATE_NNC NOT NULL,
  END_DATE           DATE,
  CREATED_BY         NUMBER CONSTRAINT PPSC_CREATED_BY_NNC NOT NULL,
  CREATION_DATE      DATE CONSTRAINT PPSC_CREATION_DATE_NNC NOT NULL,
  LAST_UPDATED_BY    NUMBER CONSTRAINT PPSC_LAST_UPDATED_BY_NNC NOT NULL,
  LAST_UPDATE_DATE   DATE CONSTRAINT PPSC_LAST_UPDATE_DATE_NNC NOT NULL,
  OBJECT_VERSION_ID  NUMBER CONSTRAINT PPSC_OBJECT_VERSION_ID_NNC NOT NULL,
  CONSTRAINT PPSC_ENABLED_FLAG_CK
  CHECK ( enabled_flag IN ( 'N', 'Y' ) )
  ENABLE VALIDATE
,  CONSTRAINT PPSC_STATUS_CODE_CK
  CHECK ( status_code IN ( 'A', 'D', 'I' ) )
  ENABLE VALIDATE
,  CONSTRAINT PPSC_SUB_CATEGORY_ID_PK
  PRIMARY KEY
  (SUB_CATEGORY_ID)
  ENABLE VALIDATE
,  CONSTRAINT PPSC_CATEGORY_ID_FK 
  FOREIGN KEY (CATEGORY_ID) 
  REFERENCES DEMASYLABS.POS_PRODUCT_CATEGORIES (CATEGORY_ID)
  ENABLE VALIDATE
)
LOGGING 
NOCOMPRESS 
NO INMEMORY
NOCACHE
RESULT_CACHE (MODE DEFAULT)
NOPARALLEL
/

COMMENT ON TABLE DEMASYLABS.POS_PRODUCT_SUB_CATEGORIES IS 'Product sub-category table for second-level product classification. Provides detailed categorization within main product categories for enhanced inventory organization and customer navigation in the POS system.'
/

COMMENT ON COLUMN DEMASYLABS.POS_PRODUCT_SUB_CATEGORIES.SUB_CATEGORY_ID IS 'Primary identifier for product sub-categories'
/

COMMENT ON COLUMN DEMASYLABS.POS_PRODUCT_SUB_CATEGORIES.CATEGORY_ID IS 'Foreign key reference to parent product category'
/

COMMENT ON COLUMN DEMASYLABS.POS_PRODUCT_SUB_CATEGORIES.DISPLAY_ORDER IS 'Sort order for sub-category displays within parent category'
/

COMMENT ON COLUMN DEMASYLABS.POS_PRODUCT_SUB_CATEGORIES.SHORT_NAME IS 'Abbreviated sub-category name for reports and compact displays'
/

COMMENT ON COLUMN DEMASYLABS.POS_PRODUCT_SUB_CATEGORIES.DESCRIPTION IS 'Sub-category description and product classification guidelines'
/

COMMENT ON COLUMN DEMASYLABS.POS_PRODUCT_SUB_CATEGORIES.STATUS_CODE IS 'Sub-category operational status: A=Active, I=Inactive, D=Discontinued'
/

COMMENT ON COLUMN DEMASYLABS.POS_PRODUCT_SUB_CATEGORIES.ENABLED_FLAG IS 'Active status (Y/N)'
/

COMMENT ON COLUMN DEMASYLABS.POS_PRODUCT_SUB_CATEGORIES.START_DATE IS 'Effective start date'
/

COMMENT ON COLUMN DEMASYLABS.POS_PRODUCT_SUB_CATEGORIES.END_DATE IS 'Effective end date'
/

COMMENT ON COLUMN DEMASYLABS.POS_PRODUCT_SUB_CATEGORIES.CREATED_BY IS 'User who created the record'
/

COMMENT ON COLUMN DEMASYLABS.POS_PRODUCT_SUB_CATEGORIES.CREATION_DATE IS 'Record creation timestamp'
/

COMMENT ON COLUMN DEMASYLABS.POS_PRODUCT_SUB_CATEGORIES.LAST_UPDATED_BY IS 'User who last updated the record'
/

COMMENT ON COLUMN DEMASYLABS.POS_PRODUCT_SUB_CATEGORIES.LAST_UPDATE_DATE IS 'Last update timestamp'
/

COMMENT ON COLUMN DEMASYLABS.POS_PRODUCT_SUB_CATEGORIES.OBJECT_VERSION_ID IS 'Optimistic locking version number'
/
