SET DEFINE OFF;
CREATE TABLE DEMASYLABS.POS_ORDERS
(
  ORDER_ID           NUMBER CONSTRAINT PO_ORDER_ID_NNC NOT NULL,
  BRANCH_ID          NUMBER(10) CONSTRAINT PO_BRANCH_ID_NNC NOT NULL,
  CASHIER_ID         NUMBER CONSTRAINT PO_CASHIER_ID_NNC NOT NULL,
  CUSTOMER_ID        NUMBER CONSTRAINT PO_CUSTOMER_ID_NNC NOT NULL,
  ORDER_TYPE         VARCHAR2(1 CHAR) CONSTRAINT PO_ORDER_TYPE_NNC NOT NULL,
  ORDER_NUMBER       VARCHAR2(30 CHAR) CONSTRAINT PO_ORDER_NUMBER_NNC NOT NULL,
  ORDER_DATE         DATE CONSTRAINT PO_ORDER_DATE_NNC NOT NULL,
  STATUS             VARCHAR2(30 CHAR) CONSTRAINT PO_STATUS_NNC NOT NULL,
  DESCRIPTION        VARCHAR2(4000 CHAR),
  HOLD_FLAG          VARCHAR2(1 CHAR)           DEFAULT 'N',
  GIFTWRAP_FLAG      VARCHAR2(1 CHAR),
  GIFTWRAP_MESSAGE   VARCHAR2(2000 CHAR),
  SUB_TOTAL          NUMBER(12,2),
  TAX_AMOUNT         NUMBER(12,2),
  DISCOUNT_AMOUNT    NUMBER(12,2),
  SHIPPING_COST      NUMBER(12,2),
  TOTAL_AMOUNT       NUMBER(12,2),
  CURRENCY_CODE      VARCHAR2(30 CHAR) CONSTRAINT PO_CURRENCY_CODE_NNC NOT NULL,
  PAYMENT_STATUS     VARCHAR2(30 CHAR) CONSTRAINT PO_PAYMENT_STATUS_NNC NOT NULL,
  PAYMENT_METHOD     VARCHAR2(30 CHAR) CONSTRAINT PO_PAYMENT_METHOD_NNC NOT NULL,
  REFERENCE_NUMBER   VARCHAR2(30 CHAR) CONSTRAINT PO_REFERENCE_NUMBER_NNC NOT NULL,
  DELIVERY_DATE      DATE,
  DELIVERY_ADDRESS   VARCHAR2(4000 CHAR),
  DELIVERY_NOTES     VARCHAR2(4000 CHAR),
  STATUS_CODE        VARCHAR2(30 CHAR)          DEFAULT 'A' CONSTRAINT PO_STATUS_CODE_NNC NOT NULL,
  ENABLED_FLAG       VARCHAR2(1 CHAR)           DEFAULT 'Y' CONSTRAINT PO_ENABLED_FLAG_NNC NOT NULL,
  START_DATE         DATE                       DEFAULT sysdate CONSTRAINT PO_START_DATE_NNC NOT NULL,
  END_DATE           DATE,
  CREATED_BY         NUMBER CONSTRAINT PO_CREATED_BY_NNC NOT NULL,
  CREATION_DATE      DATE CONSTRAINT PO_CREATION_DATE_NNC NOT NULL,
  LAST_UPDATED_BY    NUMBER CONSTRAINT PO_LAST_UPDATED_BY_NNC NOT NULL,
  LAST_UPDATE_DATE   DATE CONSTRAINT PO_LAST_UPDATE_DATE_NNC NOT NULL,
  OBJECT_VERSION_ID  NUMBER CONSTRAINT PO_OBJECT_VERSION_ID_NNC NOT NULL,
  CONSTRAINT PO_ENABLED_FLAG_CK
  CHECK ( enabled_flag IN ( 'N', 'Y' ) )
  ENABLE VALIDATE
,  CONSTRAINT PO_GIFTWRAP_FLAG_CK
  CHECK ( giftwrap_flag IN ( 'N', 'Y' ) )
  ENABLE VALIDATE
,  CONSTRAINT PO_HOLD_FLAG_CK
  CHECK ( hold_flag IN ( 'N', 'Y' ) )
  ENABLE VALIDATE
,  CONSTRAINT PO_ORDER_TYPE_CK
  CHECK ( order_type IN ( 'E', 'L', 'Q', 'R', 'S' ) )
  ENABLE VALIDATE
,  CONSTRAINT PO_STATUS_CODE_CK
  CHECK ( status_code IN ( 'A', 'D', 'I', 'P' ) )
  ENABLE VALIDATE
,  CONSTRAINT PO_ORDER_ID_PK
  PRIMARY KEY
  (ORDER_ID)
  ENABLE VALIDATE
,  CONSTRAINT PO_BRANCH_ID_FK 
  FOREIGN KEY (BRANCH_ID) 
  REFERENCES DEMASYLABS.POS_STORE_BRANCHES (BRANCH_ID)
  ENABLE VALIDATE
,  CONSTRAINT PO_CASHIER_ID_FK 
  FOREIGN KEY (CASHIER_ID) 
  REFERENCES DEMASYLABS.POS_CASHIERS (CASHIER_ID)
  ENABLE VALIDATE
,  CONSTRAINT PO_CUSTOMER_ID_FK 
  FOREIGN KEY (CUSTOMER_ID) 
  REFERENCES DEMASYLABS.POS_CUSTOMERS (CUSTOMER_ID)
  ENABLE VALIDATE
,  CONSTRAINT PO_ORDER_NUMBER_UN
  UNIQUE (ORDER_NUMBER)
  ENABLE VALIDATE
)
LOGGING 
NOCOMPRESS 
NO INMEMORY
NOCACHE
RESULT_CACHE (MODE DEFAULT)
NOPARALLEL
/

COMMENT ON TABLE DEMASYLABS.POS_ORDERS IS 'Customer orders for point-of-sale transactions. Manages complete order lifecycle including financial calculations, payment processing, delivery, and status tracking. Parent table for pos_order_lines.'
/

COMMENT ON COLUMN DEMASYLABS.POS_ORDERS.ORDER_ID IS 'Unique order identifier (Primary Key)'
/

COMMENT ON COLUMN DEMASYLABS.POS_ORDERS.BRANCH_ID IS 'Store branch where order was created (FK to pos_store_branches)'
/

COMMENT ON COLUMN DEMASYLABS.POS_ORDERS.CASHIER_ID IS 'Cashier who created the order (FK to pos_cashiers)'
/

COMMENT ON COLUMN DEMASYLABS.POS_ORDERS.CUSTOMER_ID IS 'Customer placing the order (FK to pos_customers)'
/

COMMENT ON COLUMN DEMASYLABS.POS_ORDERS.ORDER_TYPE IS 'Order type: S=Sale, R=Return, E=Exchange, L=Layaway, Q=Quote'
/

COMMENT ON COLUMN DEMASYLABS.POS_ORDERS.ORDER_NUMBER IS 'Human-readable order number for customer reference'
/

COMMENT ON COLUMN DEMASYLABS.POS_ORDERS.ORDER_DATE IS 'Date when order was placed'
/

COMMENT ON COLUMN DEMASYLABS.POS_ORDERS.STATUS IS 'Order status: DRAFT, PENDING, CONFIRMED, PROCESSING, SHIPPED, DELIVERED, COMPLETED, CANCELED, RETURNED'
/

COMMENT ON COLUMN DEMASYLABS.POS_ORDERS.HOLD_FLAG IS 'Order hold flag for special processing (Y/N)'
/

COMMENT ON COLUMN DEMASYLABS.POS_ORDERS.GIFTWRAP_FLAG IS 'Gift wrapping requested flag (Y/N)'
/

COMMENT ON COLUMN DEMASYLABS.POS_ORDERS.GIFTWRAP_MESSAGE IS 'Gift message for gift wrapping'
/

COMMENT ON COLUMN DEMASYLABS.POS_ORDERS.SUB_TOTAL IS 'Order subtotal before tax and shipping'
/

COMMENT ON COLUMN DEMASYLABS.POS_ORDERS.TAX_AMOUNT IS 'Total tax amount for the order'
/

COMMENT ON COLUMN DEMASYLABS.POS_ORDERS.DISCOUNT_AMOUNT IS 'Total discount amount applied'
/

COMMENT ON COLUMN DEMASYLABS.POS_ORDERS.SHIPPING_COST IS 'Shipping and handling charges'
/

COMMENT ON COLUMN DEMASYLABS.POS_ORDERS.TOTAL_AMOUNT IS 'Final order total (subtotal + tax + shipping - discount)'
/

COMMENT ON COLUMN DEMASYLABS.POS_ORDERS.CURRENCY_CODE IS 'ISO 3-letter currency code for price denomination'
/

COMMENT ON COLUMN DEMASYLABS.POS_ORDERS.PAYMENT_STATUS IS 'Payment status: PENDING, AUTHORIZED, CAPTURED, PAID, REFUNDED, FAILED, CANCELED'
/

COMMENT ON COLUMN DEMASYLABS.POS_ORDERS.PAYMENT_METHOD IS 'Payment method used (CASH, CREDIT_CARD, DEBIT_CARD, etc.)'
/

COMMENT ON COLUMN DEMASYLABS.POS_ORDERS.REFERENCE_NUMBER IS 'External reference number (transaction ID, PO number, etc.)'
/

COMMENT ON COLUMN DEMASYLABS.POS_ORDERS.DELIVERY_DATE IS 'Requested or scheduled delivery date'
/

COMMENT ON COLUMN DEMASYLABS.POS_ORDERS.DELIVERY_ADDRESS IS 'Delivery address if different from customer address'
/

COMMENT ON COLUMN DEMASYLABS.POS_ORDERS.DELIVERY_NOTES IS 'Special delivery instructions'
/

COMMENT ON COLUMN DEMASYLABS.POS_ORDERS.STATUS_CODE IS 'Product operational status: A=Active, I=Inactive, D=Discontinued, P=Pending'
/

COMMENT ON COLUMN DEMASYLABS.POS_ORDERS.ENABLED_FLAG IS 'Active status flag (Y/N)'
/

COMMENT ON COLUMN DEMASYLABS.POS_ORDERS.START_DATE IS 'Effective start date'
/

COMMENT ON COLUMN DEMASYLABS.POS_ORDERS.END_DATE IS 'Effective end date'
/

COMMENT ON COLUMN DEMASYLABS.POS_ORDERS.CREATED_BY IS 'User who created the record'
/

COMMENT ON COLUMN DEMASYLABS.POS_ORDERS.CREATION_DATE IS 'Record creation timestamp'
/

COMMENT ON COLUMN DEMASYLABS.POS_ORDERS.LAST_UPDATED_BY IS 'User who last updated the record'
/

COMMENT ON COLUMN DEMASYLABS.POS_ORDERS.LAST_UPDATE_DATE IS 'Last update timestamp'
/

COMMENT ON COLUMN DEMASYLABS.POS_ORDERS.OBJECT_VERSION_ID IS 'Optimistic locking version number'
/
