SET DEFINE OFF;
CREATE TABLE DEMASYLABS.POS_PRODUCT_CATEGORIES
(
  CATEGORY_ID        NUMBER CONSTRAINT PPC_CATEGORY_ID_NNC NOT NULL,
  SHORT_NAME         VARCHAR2(50 CHAR) CONSTRAINT PPC_SHORT_NAME_NNC NOT NULL,
  NAME               VARCHAR2(200 CHAR) CONSTRAINT PPC_NAME_NNC NOT NULL,
  DESCRIPTION        VARCHAR2(4000 CHAR),
  STATUS_CODE        VARCHAR2(30 CHAR)          DEFAULT 'A' CONSTRAINT PPC_STATUS_CODE_NNC NOT NULL,
  ENABLED_FLAG       VARCHAR2(1 CHAR)           DEFAULT 'Y' CONSTRAINT PPC_ENABLED_FLAG_NNC NOT NULL,
  START_DATE         DATE                       DEFAULT sysdate CONSTRAINT PPC_START_DATE_NNC NOT NULL,
  END_DATE           DATE,
  CREATED_BY         NUMBER CONSTRAINT PPC_CREATED_BY_NNC NOT NULL,
  CREATION_DATE      DATE CONSTRAINT PPC_CREATION_DATE_NNC NOT NULL,
  LAST_UPDATED_BY    NUMBER CONSTRAINT PPC_LAST_UPDATED_BY_NNC NOT NULL,
  LAST_UPDATE_DATE   DATE CONSTRAINT PPC_LAST_UPDATE_DATE_NNC NOT NULL,
  OBJECT_VERSION_ID  NUMBER CONSTRAINT PPC_OBJECT_VERSION_ID_NNC NOT NULL,
  CONSTRAINT PPC_ENABLED_FLAG_CK
  CHECK ( enabled_flag IN ( 'N', 'Y' ) )
  ENABLE VALIDATE
,  CONSTRAINT PPC_STATUS_CODE_CK
  CHECK ( status_code IN ( 'A', 'I' ) )
  ENABLE VALIDATE
,  CONSTRAINT PPC_CATEGORY_ID_PK
  PRIMARY KEY
  (CATEGORY_ID)
  ENABLE VALIDATE
,  CONSTRAINT PPC_NAME_UN
  UNIQUE (NAME)
  ENABLE VALIDATE
,  CONSTRAINT PPC_SHORT_NAME_UN
  UNIQUE (SHORT_NAME)
  ENABLE VALIDATE
)
LOGGING 
NOCOMPRESS 
NO INMEMORY
NOCACHE
RESULT_CACHE (MODE DEFAULT)
NOPARALLEL
/

COMMENT ON TABLE DEMASYLABS.POS_PRODUCT_CATEGORIES IS 'Product category master table for organizing retail inventory. Provides top-level categorization for products enabling efficient inventory management, reporting, and customer navigation in the POS system.'
/

COMMENT ON COLUMN DEMASYLABS.POS_PRODUCT_CATEGORIES.CATEGORY_ID IS 'Primary identifier for product categories'
/

COMMENT ON COLUMN DEMASYLABS.POS_PRODUCT_CATEGORIES.SHORT_NAME IS 'Abbreviated category name for reports and compact displays'
/

COMMENT ON COLUMN DEMASYLABS.POS_PRODUCT_CATEGORIES.NAME IS 'Full category name for customer-facing displays and documentation'
/

COMMENT ON COLUMN DEMASYLABS.POS_PRODUCT_CATEGORIES.DESCRIPTION IS 'Category description and product classification guidelines'
/

COMMENT ON COLUMN DEMASYLABS.POS_PRODUCT_CATEGORIES.STATUS_CODE IS 'Category operational status: A=Active, I=Inactive'
/

COMMENT ON COLUMN DEMASYLABS.POS_PRODUCT_CATEGORIES.ENABLED_FLAG IS 'Active status'
/

COMMENT ON COLUMN DEMASYLABS.POS_PRODUCT_CATEGORIES.START_DATE IS 'Effective start date'
/

COMMENT ON COLUMN DEMASYLABS.POS_PRODUCT_CATEGORIES.END_DATE IS 'Effective end date'
/

COMMENT ON COLUMN DEMASYLABS.POS_PRODUCT_CATEGORIES.CREATED_BY IS 'User who created the record'
/

COMMENT ON COLUMN DEMASYLABS.POS_PRODUCT_CATEGORIES.CREATION_DATE IS 'Record creation timestamp'
/

COMMENT ON COLUMN DEMASYLABS.POS_PRODUCT_CATEGORIES.LAST_UPDATED_BY IS 'User who last updated the record'
/

COMMENT ON COLUMN DEMASYLABS.POS_PRODUCT_CATEGORIES.LAST_UPDATE_DATE IS 'Last update timestamp'
/

COMMENT ON COLUMN DEMASYLABS.POS_PRODUCT_CATEGORIES.OBJECT_VERSION_ID IS 'Optimistic locking version number'
/
