   CREATE USER "DL" IDENTIFIED BY VALUES 'DL' DEFAULT COLLATION "USING_NLS_COMP" 
      DEFAULT TABLESPACE "USERS"
      TEMPORARY TABLESPACE "TEMP";

   GRANT "CONNECT" TO "DL";
   GRANT "SELECT_CATALOG_ROLE" TO "DL";
   GRANT "EXECUTE_CATALOG_ROLE" TO "DL";

   ALTER USER "DL" DEFAULT ROLE "CONNECT", "SELECT_CATALOG_ROLE", "EXECUTE_CATALOG_ROLE";

  GRANT CREATE SESSION TO "DL";
  GRANT ALTER SESSION TO "DL";
  GRANT CREATE TABLE TO "DL";
  GRANT CREATE ANY TABLE TO "DL";
  GRANT ALTER ANY TABLE TO "DL";
  GRANT DROP ANY TABLE TO "DL";
  GRANT COMMENT ANY TABLE TO "DL";
  GRANT SELECT ANY TABLE TO "DL";
  GRANT INSERT ANY TABLE TO "DL";
  GRANT UPDATE ANY TABLE TO "DL";
  GRANT DELETE ANY TABLE TO "DL";
  GRANT CREATE ANY INDEX TO "DL";
  GRANT ALTER ANY INDEX TO "DL";
  GRANT DROP ANY INDEX TO "DL";
  GRANT CREATE SYNONYM TO "DL";
  GRANT CREATE ANY SYNONYM TO "DL";
  GRANT DROP ANY SYNONYM TO "DL";
  GRANT CREATE PUBLIC SYNONYM TO "DL";
  GRANT DROP PUBLIC SYNONYM TO "DL";
  GRANT CREATE ANY VIEW TO "DL";
  GRANT DROP ANY VIEW TO "DL";
  GRANT CREATE SEQUENCE TO "DL";
  GRANT CREATE ANY SEQUENCE TO "DL";
  GRANT ALTER ANY SEQUENCE TO "DL";
  GRANT DROP ANY SEQUENCE TO "DL";
  GRANT SELECT ANY SEQUENCE TO "DL";
  GRANT CREATE PROCEDURE TO "DL";
  GRANT ALTER ANY PROCEDURE TO "DL";
  GRANT DROP ANY PROCEDURE TO "DL";
  GRANT EXECUTE ANY PROCEDURE TO "DL";
  GRANT CREATE ANY TRIGGER TO "DL";
  GRANT ALTER ANY TRIGGER TO "DL";
  GRANT DROP ANY TRIGGER TO "DL";
  GRANT GRANT ANY PRIVILEGE TO "DL";
  GRANT CREATE ANY DIRECTORY TO "DL";
  GRANT CREATE ANY TYPE TO "DL";
  GRANT ALTER ANY TYPE TO "DL";
  GRANT DROP ANY TYPE TO "DL";
  GRANT EXECUTE ANY TYPE TO "DL";
  GRANT CREATE INDEXTYPE TO "DL";
  GRANT CREATE ANY INDEXTYPE TO "DL";
  GRANT DROP ANY INDEXTYPE TO "DL";
  GRANT EXECUTE ANY INDEXTYPE TO "DL";
  GRANT CREATE ANY CONTEXT TO "DL";
  GRANT DROP ANY CONTEXT TO "DL";
  GRANT SELECT ANY DICTIONARY TO "DL";
  GRANT DEBUG CONNECT ANY TO "DL";
  GRANT DEBUG ANY PROCEDURE TO "DL";
  GRANT EXECUTE ANY PROGRAM TO "DL";
  GRANT SELECT ANY TRANSACTION TO "DL";
  GRANT READ ANY TABLE TO "DL";

  DECLARE 
  TEMP_COUNT NUMBER; 
  SQLSTR VARCHAR2(200); 
BEGIN 
  SQLSTR := 'ALTER USER "DL" QUOTA UNLIMITED ON "USERS"';
  EXECUTE IMMEDIATE SQLSTR;
EXCEPTION 
  WHEN OTHERS THEN
    IF SQLCODE = -30041 THEN 
      SQLSTR := 'SELECT COUNT(*) FROM USER_TABLESPACES 
              WHERE TABLESPACE_NAME = ''USERS'' AND CONTENTS = ''TEMPORARY''';
      EXECUTE IMMEDIATE SQLSTR INTO TEMP_COUNT;
      IF TEMP_COUNT = 1 THEN RETURN; 
      ELSE RAISE; 
      END IF;
    ELSE
      RAISE;
    END IF;
END;
/
