-- Generated by Oracle SQL Developer Data Modeler 19.2.0.182.1216
--   at:        2020-01-21 13:58:25 AST
--   site:      Oracle Database 12cR2
--   type:      Oracle Database 12cR2
    whenever sqlerror continue;
    drop TABLE pos_cashiers cascade constraints;
    drop TABLE pos_customers cascade constraints;
    drop TABLE pos_invoices cascade constraints;
    drop TABLE pos_order_lines cascade constraints;
    drop TABLE pos_order_transfer_batches cascade constraints;
    drop TABLE pos_order_transfer_errors cascade constraints;
    drop TABLE pos_order_transfers_all cascade constraints;
    drop TABLE pos_orders cascade constraints;
    drop TABLE pos_parties cascade constraints;
    drop TABLE pos_payment_methods cascade constraints;
    drop TABLE pos_payments cascade constraints;
    drop TABLE pos_store_branchs cascade constraints;
    drop TABLE pos_stores cascade constraints;
    drop TABLE pos_warehouses cascade constraints;

--  Demasy Labs | Point of Sale solution | SaaS Version
CREATE TABLE pos_cashiers (
    cashier_id          NUMBER
        CONSTRAINT pca_cashier_id_nnc NOT NULL,
    partiy_id           NUMBER
        CONSTRAINT pca_partiy_id_nnc NOT NULL,
    cashier_number      NUMBER,
    cashier_type        VARCHAR2(1 CHAR)
        CONSTRAINT pca_cashier_type_nnc NOT NULL,
    description         VARCHAR2(4000 CHAR),
    login_user          VARCHAR2(20 CHAR),
    login_password      VARCHAR2(100 CHAR),
    start_date          DATE
        CONSTRAINT pca_start_date_nnc NOT NULL,
    end_date            DATE,
    enabled_flag        VARCHAR2(1 CHAR)
        CONSTRAINT pca_enabled_flag_nnc NOT NULL,
    hold_flag           VARCHAR2(1 CHAR),
    employee_id         NUMBER
        CONSTRAINT pca_employee_id_nnc NOT NULL,
    created_by          NUMBER
        CONSTRAINT pca_created_by_nnc NOT NULL,
    creation_date       DATE
        CONSTRAINT pca_creation_date_nnc NOT NULL,
    last_updated_by     NUMBER
        CONSTRAINT pca_last_updated_by_nnc NOT NULL,
    last_update_date    DATE
        CONSTRAINT pca_last_update_date_nnc NOT NULL,
    object_version_id   NUMBER
        CONSTRAINT pca_object_version_id_nnc NOT NULL
);

COMMENT ON TABLE pos_cashiers IS
    'Demasy Labs | Point of Sale solution | SaaS Version';

COMMENT ON COLUMN pos_cashiers.enabled_flag IS
    'identifier id';

COMMENT ON COLUMN pos_cashiers.hold_flag IS
    'identifier id';

COMMENT ON COLUMN pos_cashiers.employee_id IS
    'SaaS Key';

CREATE UNIQUE INDEX pca_cashier_id_idx ON
    pos_cashiers (
        cashier_id
    ASC );

CREATE UNIQUE INDEX pca_cashier_number_idx ON
    pos_cashiers (
        cashier_number
    ASC );

CREATE UNIQUE INDEX pca_login_user_idx ON
    pos_cashiers (
        login_user
    ASC );

CREATE INDEX pca_partiy_id_idx ON
    pos_cashiers (
        partiy_id
    ASC );

--  Demasy Labs | Point of Sale solution | SaaS Version
CREATE TABLE pos_customers (
    customer_id          NUMBER
        CONSTRAINT pc_customer_id_nnc NOT NULL,
    partiy_id            NUMBER
        CONSTRAINT pc_partiy_id_nnc NOT NULL,
    customer_number      VARCHAR2(30 BYTE)
        CONSTRAINT pc_customer_number_nnc NOT NULL,
    description          VARCHAR2(4000 BYTE),
    registered_date      DATE,
    linked_customer_id   NUMBER
        CONSTRAINT pc_linked_customer_id_nnc NOT NULL,
    start_date           DATE
        CONSTRAINT pc_start_date_nnc NOT NULL,
    end_date             DATE,
    enabled_flag         VARCHAR2(1 CHAR)
        CONSTRAINT pc_enabled_flag_nnc NOT NULL,
    hold_flag            VARCHAR2(1 CHAR),
    gender               VARCHAR2(1 CHAR),
    identifier_type      VARCHAR2(1 CHAR),
    identifier_number    VARCHAR2(100 CHAR),
    mobile_number        VARCHAR2(30 CHAR)
        CONSTRAINT pc_mobile_number_nnc NOT NULL,
    phone_number         VARCHAR2(30 CHAR),
    address              VARCHAR2(200 CHAR),
    credit_limit         NUMBER,
    children_under_18    VARCHAR2(1 CHAR),
    login_user           VARCHAR2(20 CHAR),
    login_password       VARCHAR2(30 CHAR),
    created_by           NUMBER
        CONSTRAINT pc_created_by_nnc NOT NULL,
    creation_date        DATE
        CONSTRAINT pc_creation_date_nnc NOT NULL,
    last_updated_by      NUMBER
        CONSTRAINT pc_last_updated_by_nnc NOT NULL,
    last_update_date     DATE
        CONSTRAINT pc_last_update_date_nnc NOT NULL,
    object_version_id    NUMBER
        CONSTRAINT pc_object_version_id_nnc NOT NULL
);

COMMENT ON TABLE pos_customers IS
    'Demasy Labs | Point of Sale solution | SaaS Version';

COMMENT ON COLUMN pos_customers.enabled_flag IS
    'identifier id';

COMMENT ON COLUMN pos_customers.hold_flag IS
    'identifier id';

COMMENT ON COLUMN pos_customers.gender IS
    'identifier id';

COMMENT ON COLUMN pos_customers.identifier_type IS
    'identifier id';

COMMENT ON COLUMN pos_customers.identifier_number IS
    'identifier id';

COMMENT ON COLUMN pos_customers.children_under_18 IS
    'identifier id';

CREATE UNIQUE INDEX pc_customer_id_idx ON
    pos_customers (
        customer_id
    ASC );

CREATE UNIQUE INDEX pc_customer_number_idx ON
    pos_customers (
        customer_number
    ASC );

CREATE UNIQUE INDEX pc_mobile_number_idx ON
    pos_customers (
        mobile_number
    ASC );

CREATE UNIQUE INDEX pc_login_user_idx ON
    pos_customers (
        login_user
    ASC );

CREATE INDEX pc_partiy_id_idx ON
    pos_customers (
        partiy_id
    ASC );

--  Demasy Labs | Point of Sale solution | SaaS Version
CREATE TABLE pos_invoices (
    invoice_id          NUMBER
        CONSTRAINT pi_invoice_id_nnc NOT NULL,
    order_id            NUMBER
        CONSTRAINT pi_order_id_nnc NOT NULL,
    promotion_id        NUMBER,
    invoice_number      VARCHAR2(30 CHAR)
        CONSTRAINT pi_invoice_number_nnc NOT NULL,
    description         VARCHAR2(4000 CHAR),
    amount              NUMBER
        CONSTRAINT pi_amount_nnc NOT NULL,
    currancy_code       VARCHAR2(3 CHAR)
        CONSTRAINT pi_currancy_code_nnc NOT NULL,
    enabled_flag        VARCHAR2(1 CHAR)
        CONSTRAINT pi_enabled_flag_nnc NOT NULL,
    start_date          DATE
        CONSTRAINT pi_start_date_nnc NOT NULL,
    end_date            DATE,
    created_by          NUMBER
        CONSTRAINT pi_created_by_nnc NOT NULL,
    creation_date       DATE
        CONSTRAINT pi_creation_date_nnc NOT NULL,
    last_updated_by     NUMBER
        CONSTRAINT pi_last_updated_by_nnc NOT NULL,
    last_update_date    DATE
        CONSTRAINT pi_last_update_date_nnc NOT NULL,
    object_version_id   NUMBER
        CONSTRAINT pi_object_version_id_nnc NOT NULL
);

COMMENT ON TABLE pos_invoices IS
    'Demasy Labs | Point of Sale solution | SaaS Version';

CREATE UNIQUE INDEX pi_invoice_id_idx ON
    pos_invoices (
        invoice_id
    ASC );

CREATE UNIQUE INDEX pi_invoice_number_idx ON
    pos_invoices (
        invoice_number
    ASC );

CREATE INDEX pi_order_id_idx ON
    pos_invoices (
        order_id
    ASC );

--  Demasy Labs | Point of Sale solution | SaaS Version
CREATE TABLE pos_order_lines (
    order_line_id       NUMBER
        CONSTRAINT pol_order_line_id_nnc NOT NULL,
    order_id            NUMBER
        CONSTRAINT pol_order_id_nnc NOT NULL,
    line_num            NUMBER
        CONSTRAINT pol_line_num_nnc NOT NULL,
    line_type           VARCHAR2(1 CHAR)
        CONSTRAINT pol_line_type_nnc NOT NULL,
    organization_id     NUMBER,
    inventory_item_id   NUMBER,
    price               NUMBER,
    quantity            NUMBER,
    amount              NUMBER,
    description         VARCHAR2(4000 CHAR),
    cancel_flag         VARCHAR2(1 CHAR),
    canceled_by         NUMBER,
    cancel_reason       VARCHAR2(1000 CHAR),
    start_date          DATE
        CONSTRAINT pol_start_date_nnc NOT NULL,
    end_date            DATE,
    created_by          NUMBER
        CONSTRAINT pol_created_by_nnc NOT NULL,
    creation_date       DATE
        CONSTRAINT pol_creation_date_nnc NOT NULL,
    last_updated_by     NUMBER
        CONSTRAINT pol_last_updated_by_nnc NOT NULL,
    last_update_date    DATE
        CONSTRAINT pol_last_update_date_nnc NOT NULL,
    object_version_id   NUMBER
        CONSTRAINT pol_object_version_id_nnc NOT NULL
);

COMMENT ON TABLE pos_order_lines IS
    'Demasy Labs | Point of Sale solution | SaaS Version';

COMMENT ON COLUMN pos_order_lines.line_type IS
    'P Product
S Service';

COMMENT ON COLUMN pos_order_lines.organization_id IS
    'SaaS Key';

COMMENT ON COLUMN pos_order_lines.inventory_item_id IS
    'SaaS Key';

COMMENT ON COLUMN pos_order_lines.cancel_flag IS
    ' ';

COMMENT ON COLUMN pos_order_lines.canceled_by IS
    'SaaS Key (PERSON_ID)';

COMMENT ON COLUMN pos_order_lines.cancel_reason IS
    ' ';

CREATE UNIQUE INDEX pol_order_line_id_idx ON
    pos_order_lines (
        order_line_id
    ASC );

CREATE INDEX pol_order_id_idx ON
    pos_order_lines (
        order_id
    ASC );

--  Demasy Labs | Point of Sale solution | SaaS Version
CREATE TABLE pos_order_transfer_batches (
    batch_id            NUMBER
        CONSTRAINT potb_batch_id_nnc NOT NULL,
    batch_date          DATE,
    batch_number        VARCHAR2(100 CHAR)
        CONSTRAINT potb_batch_number_nnc NOT NULL,
    description         VARCHAR2(4000 BYTE),
    posted_date         DATE,
    posted_by           NUMBER,
    start_date          DATE
        CONSTRAINT potb_start_date_nnc NOT NULL,
    end_date            DATE,
    enabled_flag        VARCHAR2(1 CHAR)
        CONSTRAINT potb_enabled_flag_nnc NOT NULL,
    created_by          VARCHAR2(60 CHAR)
        CONSTRAINT potb_created_by_nnc NOT NULL,
    creation_date       DATE
        CONSTRAINT potb_creation_date_nnc NOT NULL,
    last_updated_by     VARCHAR2(60 CHAR)
        CONSTRAINT potb_last_updated_by_nnc NOT NULL,
    last_update_date    DATE
        CONSTRAINT potb_last_update_date_nnc NOT NULL,
    object_version_id   NUMBER
        CONSTRAINT potb_object_version_id_nnc NOT NULL
);

COMMENT ON TABLE pos_order_transfer_batches IS
    'Demasy Labs | Point of Sale solution | SaaS Version';

CREATE UNIQUE INDEX potb_batch_id_idx ON
    pos_order_transfer_batches (
        batch_id
    ASC );

--  Demasy Labs | Point of Sale solution | SaaS Version
CREATE TABLE pos_order_transfer_errors (
    error_id            NUMBER
        CONSTRAINT pote_transfer_error_id_nnc NOT NULL,
    trx_id              NUMBER
        CONSTRAINT pote_trx_id_nnc NOT NULL,
    error_type          VARCHAR2(30 CHAR),
    error_code          VARCHAR2(100 CHAR),
    error_message       VARCHAR2(2000 BYTE),
    error_data          CLOB,
    start_date          DATE
        CONSTRAINT pote_start_date_nnc NOT NULL,
    end_date            DATE,
    description         VARCHAR2(4000 BYTE),
    created_by          VARCHAR2(60 CHAR)
        CONSTRAINT pote_created_by_nnc NOT NULL,
    creation_date       DATE
        CONSTRAINT pote_creation_date_nnc NOT NULL,
    last_updated_by     VARCHAR2(60 CHAR)
        CONSTRAINT pote_last_updated_by_nnc NOT NULL,
    last_update_date    DATE
        CONSTRAINT pote_last_update_date_nnc NOT NULL,
    object_version_id   NUMBER
        CONSTRAINT pote_object_version_id_nnc NOT NULL
);

COMMENT ON TABLE pos_order_transfer_errors IS
    'Demasy Labs | Point of Sale solution | SaaS Version';

CREATE UNIQUE INDEX pote_error_id_idx ON
    pos_order_transfer_errors (
        error_id
    ASC );

CREATE INDEX pote_trx_id_idx ON
    pos_order_transfer_errors (
        trx_id
    ASC );

--  Demasy Labs | Point of Sale solution | SaaS Version
CREATE TABLE pos_order_transfers_all (
    trx_id              NUMBER
        CONSTRAINT pota_trx_id_nnc NOT NULL,
    batch_id            NUMBER
        CONSTRAINT pota_batch_id_nnc NOT NULL,
    order_id            NUMBER
        CONSTRAINT pota_order_id_nnc NOT NULL,
    trx_date            DATE,
    status              VARCHAR2(10 CHAR),
    posted_date         DATE,
    linked_invoice_id   NUMBER,
    description         VARCHAR2(4000 BYTE),
    start_date          DATE
        CONSTRAINT pota_start_date_nnc NOT NULL,
    end_date            DATE,
    enabled_flag        VARCHAR2(1 CHAR)
        CONSTRAINT pota_enabled_flag_nnc NOT NULL,
    created_by          VARCHAR2(60 CHAR)
        CONSTRAINT pota_created_by_nnc NOT NULL,
    creation_date       DATE
        CONSTRAINT pota_creation_date_nnc NOT NULL,
    last_updated_by     VARCHAR2(60 CHAR)
        CONSTRAINT pota_last_updated_by_nnc NOT NULL,
    last_update_date    DATE
        CONSTRAINT pota_last_update_date_nnc NOT NULL,
    object_version_id   NUMBER
        CONSTRAINT pota_object_version_id_nnc NOT NULL
);

COMMENT ON TABLE pos_order_transfers_all IS
    'Demasy Labs | Point of Sale solution | SaaS Version';

CREATE UNIQUE INDEX pota_trx_id_idx ON
    pos_order_transfers_all (
        trx_id
    ASC );

CREATE INDEX pota_batch_id_idx ON
    pos_order_transfers_all (
        batch_id
    ASC );

CREATE INDEX pota_order_id_idx ON
    pos_order_transfers_all (
        order_id
    ASC );

--  Demasy Labs | Point of Sale solution | SaaS Version
CREATE TABLE pos_orders (
    order_id            NUMBER
        CONSTRAINT po_order_id_nnc NOT NULL,
    branch_id           NUMBER(10)
        CONSTRAINT po_branch_id_nnc NOT NULL,
    warehouse_id        NUMBER
        CONSTRAINT po_warehouse_id_nnc NOT NULL,
    cashier_id          NUMBER
        CONSTRAINT po_cashier_id_nnc NOT NULL,
    customer_id         NUMBER
        CONSTRAINT po_customer_id_nnc NOT NULL,
    order_type          VARCHAR2(1 CHAR)
        CONSTRAINT po_order_type_nnc NOT NULL,
    order_number        VARCHAR2(30 CHAR)
        CONSTRAINT po_order_number_nnc NOT NULL,
    order_date          DATE
        CONSTRAINT po_order_date_nnc NOT NULL,
    status              VARCHAR2(30 CHAR)
        CONSTRAINT po_status_nnc NOT NULL,
    description         VARCHAR2(4000 CHAR),
    enabled_flag        VARCHAR2(1 CHAR)
        CONSTRAINT po_enabled_flag_nnc NOT NULL,
    hold_flag           VARCHAR2(1 CHAR),
    giftwrap_flag       VARCHAR2(1 CHAR),
    giftwrap_message    VARCHAR2(2000 CHAR),
    start_date          DATE,
    end_date            DATE,
    created_by          NUMBER
        CONSTRAINT po_created_by_nnc NOT NULL,
    creation_date       DATE
        CONSTRAINT po_creation_date_nnc NOT NULL,
    last_updated_by     NUMBER
        CONSTRAINT po_last_updated_by_nnc NOT NULL,
    last_update_date    DATE
        CONSTRAINT po_last_update_date_nnc NOT NULL,
    object_version_id   NUMBER
        CONSTRAINT po_object_version_id_nnc NOT NULL
);

COMMENT ON TABLE pos_orders IS
    'Demasy Labs | Point of Sale solution | SaaS Version';

COMMENT ON COLUMN pos_orders.enabled_flag IS
    'identifier id';

COMMENT ON COLUMN pos_orders.hold_flag IS
    'identifier id';

CREATE UNIQUE INDEX po_order_id_idx ON
    pos_orders (
        order_id
    ASC );

CREATE UNIQUE INDEX po_order_number_idx ON
    pos_orders (
        order_number
    ASC );

CREATE INDEX po_customer_id_idx ON
    pos_orders (
        customer_id
    ASC );

CREATE INDEX po_branch_id_idx ON
    pos_orders (
        branch_id
    ASC );

CREATE INDEX po_cashier_id_idx ON
    pos_orders (
        cashier_id
    ASC );

CREATE INDEX po_warehouse_id_idx ON
    pos_orders (
        warehouse_id
    ASC );

--  Demasy Labs | Point of Sale solution | SaaS Version
CREATE TABLE pos_parties (
    partiy_id               NUMBER
        CONSTRAINT pps_partiy_id_nnc NOT NULL,
    party_type              VARCHAR2(1 CHAR)
        CONSTRAINT pps_party_type_nnc NOT NULL,
    party_number            VARCHAR2(30 BYTE)
        CONSTRAINT pps_party_number_nnc NOT NULL,
    party_name              VARCHAR2(360 CHAR)
        CONSTRAINT pps_party_name_nnc NOT NULL,
    description             VARCHAR2(4000 BYTE),
    person_title            VARCHAR2(3 CHAR),
    person_first_name       VARCHAR2(100 CHAR),
    person_middle_name      VARCHAR2(100 CHAR),
    person_last_name        VARCHAR2(100 CHAR),
    person_nice_name        VARCHAR2(100 CHAR),
    person_gender           VARCHAR2(1 CHAR),
    person_marital_status   VARCHAR2(1 CHAR),
    date_of_birth           DATE,
    start_date              DATE
        CONSTRAINT pps_start_date_nnc NOT NULL,
    end_date                DATE,
    enabled_flag            VARCHAR2(1 CHAR)
        CONSTRAINT pps_enabled_flag_nnc NOT NULL,
    hold_flag               VARCHAR2(1 CHAR),
    created_by              NUMBER
        CONSTRAINT pps_created_by_nnc NOT NULL,
    creation_date           DATE
        CONSTRAINT pps_creation_date_nnc NOT NULL,
    last_updated_by         NUMBER
        CONSTRAINT pps_last_updated_by_nnc NOT NULL,
    last_update_date        DATE
        CONSTRAINT pps_last_update_date_nnc NOT NULL,
    object_version_id       NUMBER
        CONSTRAINT pps_object_version_id_nnc NOT NULL
);

COMMENT ON TABLE pos_parties IS
    'Demasy Labs | Point of Sale solution | SaaS Version';

COMMENT ON COLUMN pos_parties.party_type IS
    'P Person, O Orgnization';

COMMENT ON COLUMN pos_parties.person_middle_name IS
    'Middle Name';

CREATE UNIQUE INDEX pps_partiy_id_idx ON
    pos_parties (
        partiy_id
    ASC );

--  Demasy Labs | Point of Sale solution | SaaS Version
CREATE TABLE pos_payment_methods (
    method_id           NUMBER
        CONSTRAINT ppm_method_id_nnc NOT NULL,
    short_name          VARCHAR2(30 CHAR),
    method_name         VARCHAR2(100 CHAR)
        CONSTRAINT ppm_method_name_nnc NOT NULL,
    method_type         VARCHAR2(1 CHAR),
    description         VARCHAR2(4000 CHAR),
    cash_flag           VARCHAR2(1 CHAR),
    default_flag        VARCHAR2(1 CHAR) DEFAULT 'N',
    enabled_flag        VARCHAR2(1 CHAR) DEFAULT 'Y'
        CONSTRAINT ppm_enabled_flag_nnc NOT NULL,
    hold_flag           VARCHAR2(1 CHAR),
    start_date          DATE
        CONSTRAINT ppm_start_date_nnc NOT NULL,
    end_date            DATE,
    created_by          NUMBER
        CONSTRAINT ppm_created_by_nnc NOT NULL,
    creation_date       DATE
        CONSTRAINT ppm_creation_date_nnc NOT NULL,
    last_updated_by     NUMBER
        CONSTRAINT ppm_last_updated_by_nnc NOT NULL,
    last_update_date    DATE
        CONSTRAINT ppm_last_update_date_nnc NOT NULL,
    object_version_id   NUMBER
        CONSTRAINT ppm_object_version_id_nnc NOT NULL
);

COMMENT ON TABLE pos_payment_methods IS
    'Demasy Labs | Point of Sale solution | SaaS Version';

CREATE UNIQUE INDEX ppm_method_id_idx ON
    pos_payment_methods (
        method_id
    ASC );

--  Demasy Labs | Point of Sale solution | SaaS Version
CREATE TABLE pos_payments (
    payment_id          NUMBER
        CONSTRAINT pp_payment_id_nnc NOT NULL,
    method_id           NUMBER
        CONSTRAINT pp_pay_method_id_nnc NOT NULL,
    invoice_id          NUMBER
        CONSTRAINT pp_invoice_id_nnc NOT NULL,
    payment_type        VARCHAR2(1 CHAR)
        CONSTRAINT pp_payment_type_nnc NOT NULL,
    payment_number      VARCHAR2(30 CHAR)
        CONSTRAINT pp_payment_number_nnc NOT NULL,
    description         VARCHAR2(4000 BYTE),
    payment_date        DATE
        CONSTRAINT pp_payment_date_nnc NOT NULL,
    payment_currancy    VARCHAR2(3 CHAR)
        CONSTRAINT pp_payment_currancy_nnc NOT NULL,
    amount              NUMBER
        CONSTRAINT pp_amount_nnc NOT NULL,
    status              VARCHAR2(1 CHAR)
        CONSTRAINT pp_status_nnc NOT NULL,
    start_date          DATE
        CONSTRAINT pp_start_date_nnc NOT NULL,
    end_date            DATE,
    enabled_flag        VARCHAR2(1 CHAR)
        CONSTRAINT pp_enabled_flag_nnc NOT NULL,
    created_by          VARCHAR2(60 CHAR)
        CONSTRAINT pp_created_by_nnc NOT NULL,
    creation_date       DATE
        CONSTRAINT pp_creation_date_nnc NOT NULL,
    last_updated_by     VARCHAR2(60 CHAR)
        CONSTRAINT pp_last_updated_by_nnc NOT NULL,
    last_update_date    DATE
        CONSTRAINT pp_last_update_date_nnc NOT NULL,
    object_version_id   NUMBER
        CONSTRAINT pp_object_version_id_nnc NOT NULL
);

COMMENT ON TABLE pos_payments IS
    'Demasy Labs | Point of Sale solution | SaaS Version';

CREATE UNIQUE INDEX pp_payment_id_idx ON
    pos_payments (
        payment_id
    ASC );

CREATE INDEX pp_method_id_idx ON
    pos_payments (
        method_id
    ASC );

CREATE INDEX pp_invoice_id_idx ON
    pos_payments (
        invoice_id
    ASC );

--  Demasy Labs | Point of Sale solution | SaaS Version
CREATE TABLE pos_store_branchs (
    branch_id           NUMBER
        CONSTRAINT psb_branch_id_nnc NOT NULL,
    store_id            NUMBER
        CONSTRAINT psb_store_id_nnc NOT NULL,
    branch_parent_id    NUMBER,
    short_name          VARCHAR2(50 CHAR)
        CONSTRAINT psb_short_name_nnc NOT NULL,
    name                VARCHAR2(100 CHAR)
        CONSTRAINT psb_name_nnc NOT NULL,
    description         VARCHAR2(4000 BYTE),
    manager_id          NUMBER,
    start_date          DATE
        CONSTRAINT psb_start_date_nnc NOT NULL,
    end_date            DATE,
    enabled_flag        VARCHAR2(1 CHAR)
        CONSTRAINT psb_enabled_flag_nnc NOT NULL,
    created_by          NUMBER
        CONSTRAINT psb_created_by_nnc NOT NULL,
    creation_date       DATE
        CONSTRAINT psb_creation_date_nnc NOT NULL,
    last_updated_by     NUMBER
        CONSTRAINT psb_last_updated_by_nnc NOT NULL,
    last_update_date    DATE
        CONSTRAINT psb_last_update_date_nnc NOT NULL,
    object_version_id   NUMBER
        CONSTRAINT psb_object_version_id_nnc NOT NULL
);

COMMENT ON TABLE pos_store_branchs IS
    'Demasy Labs | Point of Sale solution | SaaS Version';

COMMENT ON COLUMN pos_store_branchs.manager_id IS
    'SaaS Key';

CREATE UNIQUE INDEX psb_branch_id_idx ON
    pos_store_branchs (
        branch_id
    ASC );

CREATE UNIQUE INDEX psb_short_name_idx ON
    pos_store_branchs (
        short_name
    ASC );

CREATE UNIQUE INDEX psb_name_idx ON
    pos_store_branchs (
        name
    ASC );

CREATE INDEX psb_store_id_idx ON
    pos_store_branchs (
        store_id
    ASC );

--  Demasy Labs | Point of Sale solution | SaaS Version
CREATE TABLE pos_stores (
    store_id            NUMBER
        CONSTRAINT ps_store_id_nnc NOT NULL,
    country_code        VARCHAR2(3 CHAR)
        CONSTRAINT ps_country_code_nnc NOT NULL,
    short_name          VARCHAR2(50 CHAR)
        CONSTRAINT ps_short_name_nnc NOT NULL,
    name                VARCHAR2(100 CHAR)
        CONSTRAINT ps_name_nnc NOT NULL,
    description         VARCHAR2(4000 BYTE),
    start_date          DATE
        CONSTRAINT ps_start_date_nnc NOT NULL,
    end_date            DATE,
    enabled_flag        VARCHAR2(1 CHAR)
        CONSTRAINT ps_enabled_flag_nnc NOT NULL,
    created_by          NUMBER
        CONSTRAINT ps_created_by_nnc NOT NULL,
    creation_date       DATE
        CONSTRAINT ps_creation_date_nnc NOT NULL,
    last_updated_by     NUMBER
        CONSTRAINT ps_last_updated_by_nnc NOT NULL,
    last_update_date    DATE
        CONSTRAINT ps_last_update_date_nnc NOT NULL,
    object_version_id   NUMBER
        CONSTRAINT ps_object_version_id_nnc NOT NULL
);

COMMENT ON TABLE pos_stores IS
    'Demasy Labs | Point of Sale solution | SaaS Version';

COMMENT ON COLUMN pos_stores.country_code IS
    'SaaS Key';

CREATE UNIQUE INDEX ps_store_id_idx ON
    pos_stores (
        store_id
    ASC );

CREATE UNIQUE INDEX ps_short_name_idx ON
    pos_stores (
        short_name
    ASC );

CREATE UNIQUE INDEX ps_name_idx ON
    pos_stores (
        name
    ASC );

--  Demasy Labs | Point of Sale solution | SaaS Version
CREATE TABLE pos_warehouses ( warehouse_id NUMBER
    CONSTRAINT pw_warehouse_id_nnc NOT NULL,
    branch_id NUMBER
        CONSTRAINT pw_branch_id_nnc NOT NULL,
    warehouse_parent_id NUMBER,
    short_name VARCHAR2(30 CHAR)
        CONSTRAINT pw_short_name_nnc NOT NULL,
    name VARCHAR2(100 CHAR)
        CONSTRAINT pw_name_nnc NOT NULL,
    description VARCHAR2(4000 BYTE),
    start_date DATE
        CONSTRAINT pw_start_date_nnc NOT NULL,
    end_date DATE,
    enabled_flag VARCHAR2(1 CHAR)
        CONSTRAINT pw_enabled_flag_nnc NOT NULL, organization_id NUMBER, created_by NUMBER
    CONSTRAINT pw_created_by_nnc NOT NULL, creation_date DATE
    CONSTRAINT pw_creation_date_nnc NOT NULL, last_updated_by NUMBER
    CONSTRAINT pw_last_updated_by_nnc NOT NULL, last_update_date DATE
    CONSTRAINT pw_last_update_date_nnc NOT NULL,
object_version_id NUMBER
    CONSTRAINT pw_object_version_id_nnc NOT NULL
);
COMMENT ON TABLE pos_warehouses IS
    'Demasy Labs | Point of Sale solution | SaaS Version';

CREATE UNIQUE INDEX pw_warehouse_id_idx ON
    pos_warehouses (
        warehouse_id
    ASC );

CREATE UNIQUE INDEX pw_short_name_idx ON
    pos_warehouses (
        short_name
    ASC );

CREATE UNIQUE INDEX pw_name_idx ON
    pos_warehouses (
        name
    ASC );

CREATE INDEX pw_branch_id_idx ON
    pos_warehouses (
        branch_id
    ASC );

ALTER TABLE pos_cashiers ADD CONSTRAINT pca_cashier_id_pk PRIMARY KEY ( cashier_id );

ALTER TABLE pos_cashiers ADD CONSTRAINT pca_cashier_number_un UNIQUE ( cashier_number );

ALTER TABLE pos_cashiers ADD CONSTRAINT pca_login_user_un UNIQUE ( login_user );

ALTER TABLE pos_customers ADD CONSTRAINT pc_customer_id_pk PRIMARY KEY ( customer_id );

ALTER TABLE pos_customers ADD CONSTRAINT pc_customer_number_un UNIQUE ( customer_number );

ALTER TABLE pos_customers ADD CONSTRAINT pc_mobile_number_un UNIQUE ( mobile_number );

ALTER TABLE pos_customers ADD CONSTRAINT pc_login_user_un UNIQUE ( login_user );

ALTER TABLE pos_invoices ADD CONSTRAINT pi_invoice_id_pk PRIMARY KEY ( invoice_id );

ALTER TABLE pos_invoices ADD CONSTRAINT pi_invoice_number_un UNIQUE ( invoice_number );

ALTER TABLE pos_order_lines ADD CONSTRAINT pol_order_line_id_pk PRIMARY KEY ( order_line_id );

ALTER TABLE pos_order_transfer_batches ADD CONSTRAINT potb_batch_id_pk PRIMARY KEY ( batch_id );

ALTER TABLE pos_order_transfer_errors ADD CONSTRAINT pote_transfer_error_id_pk PRIMARY KEY ( error_id );

ALTER TABLE pos_order_transfers_all ADD CONSTRAINT pota_trx_id_pk PRIMARY KEY ( trx_id );

ALTER TABLE pos_orders ADD CONSTRAINT po_order_id_pk PRIMARY KEY ( order_id );

ALTER TABLE pos_orders ADD CONSTRAINT po_order_number_un UNIQUE ( order_number );

ALTER TABLE pos_parties ADD CONSTRAINT pps_partiy_id_pk PRIMARY KEY ( partiy_id );

ALTER TABLE pos_payment_methods ADD CONSTRAINT ppm_method_id_pk PRIMARY KEY ( method_id );

ALTER TABLE pos_payments ADD CONSTRAINT pp_payment_id_pk PRIMARY KEY ( payment_id );

ALTER TABLE pos_store_branchs ADD CONSTRAINT psb_branch_id_pk PRIMARY KEY ( branch_id );

ALTER TABLE pos_store_branchs ADD CONSTRAINT psb_short_name_un UNIQUE ( short_name );

ALTER TABLE pos_store_branchs ADD CONSTRAINT psb_name_un UNIQUE ( name );

ALTER TABLE pos_stores ADD CONSTRAINT ps_store_id_pk PRIMARY KEY ( store_id );

ALTER TABLE pos_stores ADD CONSTRAINT ps_short_name_un UNIQUE ( short_name );

ALTER TABLE pos_stores ADD CONSTRAINT ps_name_un UNIQUE ( name );

ALTER TABLE pos_warehouses ADD CONSTRAINT pw_warehouse_id_pk PRIMARY KEY ( warehouse_id );

ALTER TABLE pos_warehouses ADD CONSTRAINT pw_short_name_un UNIQUE ( short_name );

ALTER TABLE pos_warehouses ADD CONSTRAINT pw_name_un UNIQUE ( name );

ALTER TABLE pos_customers
    ADD CONSTRAINT pc_partiy_id_fk FOREIGN KEY ( partiy_id )
        REFERENCES pos_parties ( partiy_id )
    NOT DEFERRABLE;

ALTER TABLE pos_cashiers
    ADD CONSTRAINT pca_partiy_id_fk FOREIGN KEY ( partiy_id )
        REFERENCES pos_parties ( partiy_id )
    NOT DEFERRABLE;

ALTER TABLE pos_invoices
    ADD CONSTRAINT pi_order_id_fk FOREIGN KEY ( order_id )
        REFERENCES pos_orders ( order_id )
    NOT DEFERRABLE;

ALTER TABLE pos_orders
    ADD CONSTRAINT po_branch_id_fk FOREIGN KEY ( branch_id )
        REFERENCES pos_store_branchs ( branch_id )
    NOT DEFERRABLE;

ALTER TABLE pos_orders
    ADD CONSTRAINT po_cashier_id_fk FOREIGN KEY ( cashier_id )
        REFERENCES pos_cashiers ( cashier_id )
    NOT DEFERRABLE;

ALTER TABLE pos_orders
    ADD CONSTRAINT po_customer_id_fk FOREIGN KEY ( customer_id )
        REFERENCES pos_customers ( customer_id )
    NOT DEFERRABLE;

ALTER TABLE pos_orders
    ADD CONSTRAINT po_warehouse_id_fk FOREIGN KEY ( warehouse_id )
        REFERENCES pos_warehouses ( warehouse_id )
    NOT DEFERRABLE;

ALTER TABLE pos_order_lines
    ADD CONSTRAINT pol_order_id_fk FOREIGN KEY ( order_id )
        REFERENCES pos_orders ( order_id )
    NOT DEFERRABLE;

ALTER TABLE pos_order_transfers_all
    ADD CONSTRAINT pota_batch_id_fk FOREIGN KEY ( batch_id )
        REFERENCES pos_order_transfer_batches ( batch_id )
    NOT DEFERRABLE;

ALTER TABLE pos_order_transfers_all
    ADD CONSTRAINT pota_order_id_fk FOREIGN KEY ( order_id )
        REFERENCES pos_orders ( order_id )
    NOT DEFERRABLE;

ALTER TABLE pos_order_transfer_errors
    ADD CONSTRAINT pote_trx_id_fk FOREIGN KEY ( trx_id )
        REFERENCES pos_order_transfers_all ( trx_id )
    NOT DEFERRABLE;

ALTER TABLE pos_payments
    ADD CONSTRAINT pp_invoice_id_fk FOREIGN KEY ( invoice_id )
        REFERENCES pos_invoices ( invoice_id )
    NOT DEFERRABLE;

ALTER TABLE pos_payments
    ADD CONSTRAINT pp_method_id_fk FOREIGN KEY ( method_id )
        REFERENCES pos_payment_methods ( method_id )
    NOT DEFERRABLE;

ALTER TABLE pos_store_branchs
    ADD CONSTRAINT psb_store_id_fk FOREIGN KEY ( store_id )
        REFERENCES pos_stores ( store_id )
    NOT DEFERRABLE;

ALTER TABLE pos_warehouses
    ADD CONSTRAINT pw_branch_id_fk FOREIGN KEY ( branch_id )
        REFERENCES pos_store_branchs ( branch_id )
    NOT DEFERRABLE;

DROP SEQUENCE pos_cashier_id_seq;

CREATE SEQUENCE pos_cashier_id_seq START WITH 1 NOCACHE ORDER;

CREATE OR REPLACE TRIGGER pos_cashier_id_seq_trg BEFORE
    INSERT ON pos_cashiers
    FOR EACH ROW
    WHEN ( new.cashier_id IS NULL )
BEGIN
    :new.cashier_id := pos_cashier_id_seq.nextval;
END;
/

DROP SEQUENCE pos_customer_id_seq;

CREATE SEQUENCE pos_customer_id_seq START WITH 1 NOCACHE ORDER;

CREATE OR REPLACE TRIGGER pos_customer_id_seq_trg BEFORE
    INSERT ON pos_customers
    FOR EACH ROW
    WHEN ( new.customer_id IS NULL )
BEGIN
    :new.customer_id := pos_customer_id_seq.nextval;
END;
/

DROP SEQUENCE pos_invoice_id_seq;

CREATE SEQUENCE pos_invoice_id_seq START WITH 1 NOCACHE ORDER;

CREATE OR REPLACE TRIGGER pos_invoice_id_seq_trg BEFORE
    INSERT ON pos_invoices
    FOR EACH ROW
    WHEN ( new.invoice_id IS NULL )
BEGIN
    :new.invoice_id := pos_invoice_id_seq.nextval;
END;
/

DROP SEQUENCE pos_order_line_id_seq;

CREATE SEQUENCE pos_order_line_id_seq START WITH 1 NOCACHE ORDER;

CREATE OR REPLACE TRIGGER pos_order_line_id_seq_trg BEFORE
    INSERT ON pos_order_lines
    FOR EACH ROW
    WHEN ( new.order_line_id IS NULL )
BEGIN
    :new.order_line_id := pos_order_line_id_seq.nextval;
END;
/

DROP SEQUENCE pos_batch_id_seq;

CREATE SEQUENCE pos_batch_id_seq START WITH 1 NOCACHE ORDER;

CREATE OR REPLACE TRIGGER pos_batch_id_seq_trg BEFORE
    INSERT ON pos_order_transfer_batches
    FOR EACH ROW
    WHEN ( new.batch_id IS NULL )
BEGIN
    :new.batch_id := pos_batch_id_seq.nextval;
END;
/

DROP SEQUENCE pos_error_id_seq;

CREATE SEQUENCE pos_error_id_seq START WITH 1 NOCACHE ORDER;

CREATE OR REPLACE TRIGGER pos_error_id_seq_trg BEFORE
    INSERT ON pos_order_transfer_errors
    FOR EACH ROW
    WHEN ( new.error_id IS NULL )
BEGIN
    :new.error_id := pos_error_id_seq.nextval;
END;
/

DROP SEQUENCE pos_trx_id_seq;

CREATE SEQUENCE pos_trx_id_seq START WITH 1 NOCACHE ORDER;

CREATE OR REPLACE TRIGGER pos_trx_id_seq_trg BEFORE
    INSERT ON pos_order_transfers_all
    FOR EACH ROW
    WHEN ( new.trx_id IS NULL )
BEGIN
    :new.trx_id := pos_trx_id_seq.nextval;
END;
/

DROP SEQUENCE pos_order_id_seq;

CREATE SEQUENCE pos_order_id_seq START WITH 1 NOCACHE ORDER;

CREATE OR REPLACE TRIGGER pos_order_id_seq_trg BEFORE
    INSERT ON pos_orders
    FOR EACH ROW
    WHEN ( new.order_id IS NULL )
BEGIN
    :new.order_id := pos_order_id_seq.nextval;
END;
/

DROP SEQUENCE pos_partiy_id_seq;

CREATE SEQUENCE pos_partiy_id_seq START WITH 1 NOCACHE ORDER;

CREATE OR REPLACE TRIGGER pos_partiy_id_seq_trg BEFORE
    INSERT ON pos_parties
    FOR EACH ROW
    WHEN ( new.partiy_id IS NULL )
BEGIN
    :new.partiy_id := pos_partiy_id_seq.nextval;
END;
/

DROP SEQUENCE pos_method_id_seq;

CREATE SEQUENCE pos_method_id_seq START WITH 1 NOCACHE ORDER;

CREATE OR REPLACE TRIGGER pos_method_id_seq_trg BEFORE
    INSERT ON pos_payment_methods
    FOR EACH ROW
    WHEN ( new.method_id IS NULL )
BEGIN
    :new.method_id := pos_method_id_seq.nextval;
END;
/

DROP SEQUENCE pos_payment_id_seq;

CREATE SEQUENCE pos_payment_id_seq START WITH 1 NOCACHE ORDER;

CREATE OR REPLACE TRIGGER pos_payment_id_seq_trg BEFORE
    INSERT ON pos_payments
    FOR EACH ROW
    WHEN ( new.payment_id IS NULL )
BEGIN
    :new.payment_id := pos_payment_id_seq.nextval;
END;
/

DROP SEQUENCE pos_branch_id_seq;

CREATE SEQUENCE pos_branch_id_seq START WITH 1 NOCACHE ORDER;

CREATE OR REPLACE TRIGGER pos_branch_id_seq_trg BEFORE
    INSERT ON pos_store_branchs
    FOR EACH ROW
    WHEN ( new.branch_id IS NULL )
BEGIN
    :new.branch_id := pos_branch_id_seq.nextval;
END;
/

DROP SEQUENCE pos_store_id_seq;

CREATE SEQUENCE pos_store_id_seq START WITH 1 NOCACHE ORDER;

CREATE OR REPLACE TRIGGER pos_store_id_seq_trg BEFORE
    INSERT ON pos_stores
    FOR EACH ROW
    WHEN ( new.store_id IS NULL )
BEGIN
    :new.store_id := pos_store_id_seq.nextval;
END;
/

DROP SEQUENCE pos_warehouse_id_seq;

CREATE SEQUENCE pos_warehouse_id_seq START WITH 1 NOCACHE ORDER;

CREATE OR REPLACE TRIGGER pos_warehouse_id_seq_trg BEFORE
    INSERT ON pos_warehouses
    FOR EACH ROW
    WHEN ( new.warehouse_id IS NULL )
BEGIN
    :new.warehouse_id := pos_warehouse_id_seq.nextval;
END;
/

-- Oracle SQL Developer Data Modeler Summary Report: 
-- 
-- CREATE TABLE                            14
-- CREATE INDEX                            42
-- ALTER TABLE                             42
-- CREATE VIEW                              0
-- ALTER VIEW                               0
-- CREATE PACKAGE                           0
-- CREATE PACKAGE BODY                      0
-- CREATE PROCEDURE                         0
-- CREATE FUNCTION                          0
-- CREATE TRIGGER                          14
-- ALTER TRIGGER                            0
-- CREATE COLLECTION TYPE                   0
-- CREATE STRUCTURED TYPE                   0
-- CREATE STRUCTURED TYPE BODY              0
-- CREATE CLUSTER                           0
-- CREATE CONTEXT                           0
-- CREATE DATABASE                          0
-- CREATE DIMENSION                         0
-- CREATE DIRECTORY                         0
-- CREATE DISK GROUP                        0
-- CREATE ROLE                              0
-- CREATE ROLLBACK SEGMENT                  0
-- CREATE SEQUENCE                         14
-- CREATE MATERIALIZED VIEW                 0
-- CREATE MATERIALIZED VIEW LOG             0
-- CREATE SYNONYM                           0
-- CREATE TABLESPACE                        0
-- CREATE USER                              0
-- 
-- DROP TABLESPACE                          0
-- DROP DATABASE                            0
-- 
-- REDACTION POLICY                         0
-- 
-- ORDS DROP SCHEMA                         0
-- ORDS ENABLE SCHEMA                       0
-- ORDS ENABLE OBJECT                       0
-- 
-- ERRORS                                   0
-- WARNINGS                                 0
